-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity control_kernel73 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_g0_0_AWVALID : OUT STD_LOGIC;
    m_axi_g0_0_AWREADY : IN STD_LOGIC;
    m_axi_g0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_g0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_WVALID : OUT STD_LOGIC;
    m_axi_g0_0_WREADY : IN STD_LOGIC;
    m_axi_g0_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_WLAST : OUT STD_LOGIC;
    m_axi_g0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_ARVALID : OUT STD_LOGIC;
    m_axi_g0_0_ARREADY : IN STD_LOGIC;
    m_axi_g0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_g0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_RVALID : IN STD_LOGIC;
    m_axi_g0_0_RREADY : OUT STD_LOGIC;
    m_axi_g0_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_RLAST : IN STD_LOGIC;
    m_axi_g0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_g0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_BVALID : IN STD_LOGIC;
    m_axi_g0_0_BREADY : OUT STD_LOGIC;
    m_axi_g0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    v410 : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of control_kernel73 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv15_6000 : STD_LOGIC_VECTOR (14 downto 0) := "110000000000000";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv32_3F800000 : STD_LOGIC_VECTOR (31 downto 0) := "00111111100000000000000000000000";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp3_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp5_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp5 : BOOLEAN;
    signal icmp_ln1011_fu_173_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal g0_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal g0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_grp2 : BOOLEAN;
    signal g0_blk_n_AW : STD_LOGIC;
    signal ap_block_pp0_stage0_grp3 : BOOLEAN;
    signal g0_blk_n_W : STD_LOGIC;
    signal g0_blk_n_B : STD_LOGIC;
    signal ap_block_pp0_stage0_grp5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal g0_addr_reg_371 : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_reg_371_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_reg_371_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_reg_371_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_reg_371_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_reg_371_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_reg_371_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_reg_371_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_reg_371_pp0_iter8_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_reg_371_pp0_iter9_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_reg_371_pp0_iter10_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_read_reg_380 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001_grp2 : BOOLEAN;
    signal tmp_reg_385 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1016_fu_310_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln1016_reg_390 : STD_LOGIC_VECTOR (22 downto 0);
    signal icmp_ln1016_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1016_reg_400 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1016_1_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1016_1_reg_405 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1018_fu_338_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln1018_reg_410 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln1015_fu_269_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp5 : BOOLEAN;
    signal v414_fu_100 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln1012_fu_279_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_v414_load : STD_LOGIC_VECTOR (6 downto 0);
    signal v413_fu_104 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal select_ln1011_1_fu_211_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_sig_allocacmp_v413_load : STD_LOGIC_VECTOR (8 downto 0);
    signal indvar_flatten_fu_108 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal add_ln1011_1_fu_179_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_150_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln1012_fu_197_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1011_fu_191_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln_fu_219_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln1011_fu_203_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln1015_fu_231_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln1015_1_fu_235_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1015_fu_243_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln1015_fu_247_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1012_fu_227_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln1015_1_fu_253_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln_fu_259_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal or_ln1016_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal v416_fu_332_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_150_ce : STD_LOGIC;
    signal ap_block_pp0_stage0_00001_grp2 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter14_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter15_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter16_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component control_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component control_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fcmp_32ns_32ns_1_2_no_dsp_1_U456 : component control_fcmp_32ns_32ns_1_2_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 1)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_150_p0,
        din1 => ap_const_lv32_0,
        ce => grp_fu_150_ce,
        opcode => ap_const_lv5_3,
        dout => grp_fu_150_p2);

    flow_control_loop_pipe_sequential_init_U : component control_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2)) then 
                    ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp3_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3)) then 
                    ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp5_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5)) then 
                    ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln1011_fu_173_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_108 <= add_ln1011_1_fu_179_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_108 <= ap_const_lv15_0;
                end if;
            end if; 
        end if;
    end process;

    v413_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln1011_fu_173_p2 = ap_const_lv1_0))) then 
                    v413_fu_104 <= select_ln1011_1_fu_211_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    v413_fu_104 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;

    v414_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln1011_fu_173_p2 = ap_const_lv1_0))) then 
                    v414_fu_100 <= add_ln1012_fu_279_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    v414_fu_100 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
                ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
                ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                g0_addr_reg_371_pp0_iter10_reg <= g0_addr_reg_371_pp0_iter9_reg;
                g0_addr_reg_371_pp0_iter2_reg <= g0_addr_reg_371_pp0_iter1_reg;
                g0_addr_reg_371_pp0_iter3_reg <= g0_addr_reg_371_pp0_iter2_reg;
                g0_addr_reg_371_pp0_iter4_reg <= g0_addr_reg_371_pp0_iter3_reg;
                g0_addr_reg_371_pp0_iter5_reg <= g0_addr_reg_371_pp0_iter4_reg;
                g0_addr_reg_371_pp0_iter6_reg <= g0_addr_reg_371_pp0_iter5_reg;
                g0_addr_reg_371_pp0_iter7_reg <= g0_addr_reg_371_pp0_iter6_reg;
                g0_addr_reg_371_pp0_iter8_reg <= g0_addr_reg_371_pp0_iter7_reg;
                g0_addr_reg_371_pp0_iter9_reg <= g0_addr_reg_371_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                g0_addr_reg_371 <= sext_ln1015_fu_269_p1;
                g0_addr_reg_371_pp0_iter1_reg <= g0_addr_reg_371;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg))) then
                g0_addr_read_reg_380 <= m_axi_g0_0_RDATA;
                icmp_ln1016_1_reg_405 <= icmp_ln1016_1_fu_323_p2;
                icmp_ln1016_reg_400 <= icmp_ln1016_fu_318_p2;
                    select_ln1018_reg_410(29 downto 23) <= select_ln1018_fu_338_p3(29 downto 23);
                tmp_reg_385 <= m_axi_g0_0_RDATA(30 downto 23);
                trunc_ln1016_reg_390 <= trunc_ln1016_fu_310_p1;
            end if;
        end if;
    end process;
    select_ln1018_reg_410(22 downto 0) <= "00000000000000000000000";
    select_ln1018_reg_410(31 downto 30) <= "00";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1011_1_fu_179_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv15_1));
    add_ln1011_fu_191_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_v413_load) + unsigned(ap_const_lv9_1));
    add_ln1012_fu_279_p2 <= std_logic_vector(unsigned(select_ln1011_fu_203_p3) + unsigned(ap_const_lv7_1));
    add_ln1015_1_fu_253_p2 <= std_logic_vector(unsigned(add_ln1015_fu_247_p2) + unsigned(zext_ln1012_fu_227_p1));
    add_ln1015_fu_247_p2 <= std_logic_vector(unsigned(zext_ln1015_fu_243_p1) + unsigned(v410));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_00001_grp2_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_g0_0_RVALID, ap_block_pp0_stage0_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage0_00001_grp2 <= ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (m_axi_g0_0_RVALID = ap_const_logic_0));
    end process;


    ap_block_pp0_stage0_01001_grp2_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_g0_0_RVALID, ap_block_pp0_stage0_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage0_01001_grp2 <= ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (m_axi_g0_0_RVALID = ap_const_logic_0));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter17, m_axi_g0_0_AWREADY, m_axi_g0_0_WREADY, m_axi_g0_0_ARREADY, m_axi_g0_0_RVALID, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0)) or ((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg)) or ((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (m_axi_g0_0_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (m_axi_g0_0_ARREADY = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_g0_0_ARREADY, ap_block_pp0_stage0_subdone_grp1_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (m_axi_g0_0_ARREADY = ap_const_logic_0));
    end process;


    ap_block_pp0_stage0_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter12, m_axi_g0_0_WREADY, m_axi_g0_0_RVALID, ap_block_pp0_stage0_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp2 <= (((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (m_axi_g0_0_RVALID = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter11, m_axi_g0_0_AWREADY, ap_block_pp0_stage0_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp3 <= ((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp5_assign_proc : process(ap_enable_reg_pp0_iter17, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp5 <= ((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter17, m_axi_g0_0_AWREADY, m_axi_g0_0_WREADY, m_axi_g0_0_ARREADY, m_axi_g0_0_RVALID, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0)) or ((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg)) or ((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (m_axi_g0_0_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (m_axi_g0_0_ARREADY = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_subdone_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_g0_0_ARREADY, ap_block_pp0_stage0_subdone_grp1_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (m_axi_g0_0_ARREADY = ap_const_logic_0));
    end process;


    ap_block_pp0_stage0_subdone_grp2_assign_proc : process(ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter12, m_axi_g0_0_WREADY, m_axi_g0_0_RVALID, ap_block_pp0_stage0_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp2 <= (((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (m_axi_g0_0_RVALID = ap_const_logic_0)));
    end process;


    ap_block_pp0_stage0_subdone_grp3_assign_proc : process(ap_enable_reg_pp0_iter11, m_axi_g0_0_AWREADY, ap_block_pp0_stage0_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp3 <= ((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp5_assign_proc : process(ap_enable_reg_pp0_iter17, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp5 <= ((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln1011_fu_173_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1011_fu_173_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter16_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter16_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17)
    begin
        if (((ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_108)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv15_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_108;
        end if; 
    end process;


    ap_sig_allocacmp_v413_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, v413_fu_104)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_v413_load <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_v413_load <= v413_fu_104;
        end if; 
    end process;


    ap_sig_allocacmp_v414_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, v414_fu_100, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_v414_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_v414_load <= v414_fu_100;
        end if; 
    end process;


    g0_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_g0_0_ARREADY, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg))) then 
            g0_blk_n_AR <= m_axi_g0_0_ARREADY;
        else 
            g0_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_AW_assign_proc : process(ap_enable_reg_pp0_iter11, m_axi_g0_0_AWREADY, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_grp3)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg))) then 
            g0_blk_n_AW <= m_axi_g0_0_AWREADY;
        else 
            g0_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_B_assign_proc : process(ap_enable_reg_pp0_iter17, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_pp0_stage0_grp5)
    begin
        if (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg))) then 
            g0_blk_n_B <= m_axi_g0_0_BVALID;
        else 
            g0_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_g0_0_RVALID, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage0_grp2)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg))) then 
            g0_blk_n_R <= m_axi_g0_0_RVALID;
        else 
            g0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter12, m_axi_g0_0_WREADY, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage0_grp2)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg))) then 
            g0_blk_n_W <= m_axi_g0_0_WREADY;
        else 
            g0_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_150_ce_assign_proc : process(ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage0_11001_grp2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg))) then 
            grp_fu_150_ce <= ap_const_logic_1;
        else 
            grp_fu_150_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_150_p0 <= g0_addr_read_reg_380;
    icmp_ln1011_fu_173_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv15_6000) else "0";
    icmp_ln1012_fu_197_p2 <= "1" when (ap_sig_allocacmp_v414_load = ap_const_lv7_40) else "0";
    icmp_ln1016_1_fu_323_p2 <= "1" when (trunc_ln1016_reg_390 = ap_const_lv23_0) else "0";
    icmp_ln1016_fu_318_p2 <= "0" when (tmp_reg_385 = ap_const_lv8_FF) else "1";
    m_axi_g0_0_ARADDR <= g0_addr_reg_371;
    m_axi_g0_0_ARBURST <= ap_const_lv2_0;
    m_axi_g0_0_ARCACHE <= ap_const_lv4_0;
    m_axi_g0_0_ARID <= ap_const_lv1_0;
    m_axi_g0_0_ARLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_g0_0_ARLOCK <= ap_const_lv2_0;
    m_axi_g0_0_ARPROT <= ap_const_lv3_0;
    m_axi_g0_0_ARQOS <= ap_const_lv4_0;
    m_axi_g0_0_ARREGION <= ap_const_lv4_0;
    m_axi_g0_0_ARSIZE <= ap_const_lv3_0;
    m_axi_g0_0_ARUSER <= ap_const_lv1_0;

    m_axi_g0_0_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg))) then 
            m_axi_g0_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_g0_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_g0_0_AWADDR <= g0_addr_reg_371_pp0_iter10_reg;
    m_axi_g0_0_AWBURST <= ap_const_lv2_0;
    m_axi_g0_0_AWCACHE <= ap_const_lv4_0;
    m_axi_g0_0_AWID <= ap_const_lv1_0;
    m_axi_g0_0_AWLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_g0_0_AWLOCK <= ap_const_lv2_0;
    m_axi_g0_0_AWPROT <= ap_const_lv3_0;
    m_axi_g0_0_AWQOS <= ap_const_lv4_0;
    m_axi_g0_0_AWREGION <= ap_const_lv4_0;
    m_axi_g0_0_AWSIZE <= ap_const_lv3_0;
    m_axi_g0_0_AWUSER <= ap_const_lv1_0;

    m_axi_g0_0_AWVALID_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_11001_grp3)
    begin
        if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg))) then 
            m_axi_g0_0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_g0_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_g0_0_BREADY_assign_proc : process(ap_enable_reg_pp0_iter17, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_pp0_stage0_11001_grp5)
    begin
        if (((ap_enable_reg_pp0_iter17 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg))) then 
            m_axi_g0_0_BREADY <= ap_const_logic_1;
        else 
            m_axi_g0_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_g0_0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage0_11001_grp2)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg))) then 
            m_axi_g0_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_g0_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_g0_0_WDATA <= select_ln1018_reg_410;
    m_axi_g0_0_WID <= ap_const_lv1_0;
    m_axi_g0_0_WLAST <= ap_const_logic_0;
    m_axi_g0_0_WSTRB <= ap_const_lv4_F;
    m_axi_g0_0_WUSER <= ap_const_lv1_0;

    m_axi_g0_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage0_11001_grp2)
    begin
        if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg))) then 
            m_axi_g0_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_g0_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    or_ln1016_fu_328_p2 <= (icmp_ln1016_reg_400 or icmp_ln1016_1_reg_405);
    select_ln1011_1_fu_211_p3 <= 
        add_ln1011_fu_191_p2 when (icmp_ln1012_fu_197_p2(0) = '1') else 
        ap_sig_allocacmp_v413_load;
    select_ln1011_fu_203_p3 <= 
        ap_const_lv7_0 when (icmp_ln1012_fu_197_p2(0) = '1') else 
        ap_sig_allocacmp_v414_load;
    select_ln1018_fu_338_p3 <= 
        ap_const_lv32_3F800000 when (v416_fu_332_p2(0) = '1') else 
        ap_const_lv32_0;
        sext_ln1015_fu_269_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_259_p4),64));

    shl_ln1015_1_fu_235_p3 <= (trunc_ln1015_fu_231_p1 & ap_const_lv2_0);
    shl_ln_fu_219_p3 <= (select_ln1011_1_fu_211_p3 & ap_const_lv8_0);
    trunc_ln1015_fu_231_p1 <= select_ln1011_fu_203_p3(6 - 1 downto 0);
    trunc_ln1016_fu_310_p1 <= m_axi_g0_0_RDATA(23 - 1 downto 0);
    trunc_ln_fu_259_p4 <= add_ln1015_1_fu_253_p2(63 downto 2);
    v416_fu_332_p2 <= (or_ln1016_fu_328_p2 and grp_fu_150_p2);
    zext_ln1012_fu_227_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_219_p3),64));
    zext_ln1015_fu_243_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1015_1_fu_235_p3),64));
end behav;
