[hls]
relative_roots=/home/hwx/HCA/FPGA-SNN/vitis_ws/vitis_ws_spikingformer_official
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=kernel25/anonymous 
syn.directive.pipeline=kernel68/VITIS_LOOP_929_2 
syn.directive.pipeline=kernel42/anonymous 
syn.directive.pipeline=kernel9/anonymous 
syn.directive.pipeline=control/anonymous 
syn.directive.pipeline=control/anonymous 
syn.directive.pipeline=control/anonymous 
syn.directive.pipeline=control/anonymous 
syn.directive.pipeline=control/anonymous 
syn.directive.pipeline=control/VITIS_LOOP_899_3 
syn.directive.pipeline=control/VITIS_LOOP_589_2 
syn.directive.pipeline=control/VITIS_LOOP_99_2 
syn.directive.pipeline=control/VITIS_LOOP_74_2 
syn.directive.pipeline=control/anonymous 
# Inferred from Performance Budgeter performance directives
syn.directive.loop_flatten=control/VITIS_LOOP_73_1  
syn.directive.loop_flatten=control/VITIS_LOOP_588_1  
syn.directive.loop_flatten=control/VITIS_LOOP_898_2  
syn.directive.loop_flatten=control/VITIS_LOOP_897_1  
syn.directive.loop_flatten=kernel68/VITIS_LOOP_928_1  
# Inferred from performance & pipeline pragmas/directives
syn.directive.loop_flatten=control/VITIS_LOOP_42_1  
syn.directive.loop_flatten=kernel7/VITIS_LOOP_124_2  
syn.directive.loop_flatten=kernel7/VITIS_LOOP_123_1  
syn.directive.loop_flatten=kernel8/VITIS_LOOP_146_2 off
syn.directive.loop_flatten=kernel8/VITIS_LOOP_147_3  
syn.directive.loop_flatten=kernel9/VITIS_LOOP_174_2  
syn.directive.loop_flatten=kernel9/VITIS_LOOP_173_1  
syn.directive.loop_flatten=kernel10/VITIS_LOOP_191_2  
syn.directive.loop_flatten=kernel10/VITIS_LOOP_190_1  
syn.directive.loop_flatten=control/VITIS_LOOP_208_2  
syn.directive.loop_flatten=control/VITIS_LOOP_207_1  
syn.directive.loop_flatten=kernel12/VITIS_LOOP_228_2  
syn.directive.loop_flatten=kernel12/VITIS_LOOP_227_1  
syn.directive.loop_flatten=control/VITIS_LOOP_249_2  
syn.directive.loop_flatten=control/VITIS_LOOP_248_1  
syn.directive.loop_flatten=control/VITIS_LOOP_270_2  
syn.directive.loop_flatten=control/VITIS_LOOP_269_1  
syn.directive.loop_flatten=control/VITIS_LOOP_288_2  
syn.directive.loop_flatten=control/VITIS_LOOP_287_1  
syn.directive.loop_flatten=kernel18/VITIS_LOOP_306_2  
syn.directive.loop_flatten=kernel18/VITIS_LOOP_305_1  
syn.directive.loop_flatten=kernel19/VITIS_LOOP_326_2  
syn.directive.loop_flatten=kernel19/VITIS_LOOP_325_1  
syn.directive.loop_flatten=kernel24/VITIS_LOOP_346_2 off
syn.directive.loop_flatten=kernel24/VITIS_LOOP_347_3  
syn.directive.loop_flatten=kernel25/VITIS_LOOP_374_2  
syn.directive.loop_flatten=kernel25/VITIS_LOOP_373_1  
syn.directive.loop_flatten=kernel26/VITIS_LOOP_391_2  
syn.directive.loop_flatten=kernel26/VITIS_LOOP_390_1  
syn.directive.loop_flatten=kernel28/VITIS_LOOP_409_2  
syn.directive.loop_flatten=kernel28/VITIS_LOOP_408_1  
syn.directive.loop_flatten=kernel29/VITIS_LOOP_430_2  
syn.directive.loop_flatten=kernel29/VITIS_LOOP_429_1  
syn.directive.loop_flatten=kernel30/VITIS_LOOP_451_2  
syn.directive.loop_flatten=kernel30/VITIS_LOOP_450_1  
syn.directive.loop_flatten=kernel32/VITIS_LOOP_469_2  
syn.directive.loop_flatten=kernel32/VITIS_LOOP_468_1  
syn.directive.loop_flatten=kernel34/VITIS_LOOP_487_2  
syn.directive.loop_flatten=kernel34/VITIS_LOOP_486_1  
syn.directive.loop_flatten=kernel35/VITIS_LOOP_507_2  
syn.directive.loop_flatten=kernel35/VITIS_LOOP_506_1  
syn.directive.loop_flatten=kernel40/VITIS_LOOP_525_2  
syn.directive.loop_flatten=kernel40/VITIS_LOOP_524_1  
syn.directive.loop_flatten=kernel41/VITIS_LOOP_548_2 off
syn.directive.loop_flatten=kernel42/VITIS_LOOP_573_1  
syn.directive.loop_flatten=kernel44/VITIS_LOOP_600_1  
syn.directive.loop_flatten=control/VITIS_LOOP_615_1  
syn.directive.loop_flatten=kernel46/VITIS_LOOP_633_1  
syn.directive.loop_flatten=control/VITIS_LOOP_652_1  
syn.directive.loop_flatten=control/VITIS_LOOP_671_1  
syn.directive.loop_flatten=control/VITIS_LOOP_687_1  
syn.directive.loop_flatten=control/VITIS_LOOP_703_1  
syn.directive.loop_flatten=kernel53/VITIS_LOOP_721_1  
syn.directive.loop_flatten=control/VITIS_LOOP_736_1  
syn.directive.loop_flatten=control/VITIS_LOOP_752_2  
syn.directive.loop_flatten=control/VITIS_LOOP_751_1  
syn.directive.loop_flatten=kernel59/VITIS_LOOP_773_2  
syn.directive.loop_flatten=kernel59/VITIS_LOOP_772_1  
syn.directive.loop_flatten=kernel60/VITIS_LOOP_797_3  
syn.directive.loop_flatten=kernel60/VITIS_LOOP_796_2  
syn.directive.loop_flatten=kernel60/VITIS_LOOP_795_1  
syn.directive.loop_flatten=kernel61/VITIS_LOOP_820_2  
syn.directive.loop_flatten=kernel61/VITIS_LOOP_819_1  
syn.directive.loop_flatten=control/VITIS_LOOP_837_2  
syn.directive.loop_flatten=control/VITIS_LOOP_836_1  
syn.directive.loop_flatten=kernel63/VITIS_LOOP_858_3  
syn.directive.loop_flatten=kernel63/VITIS_LOOP_857_2  
syn.directive.loop_flatten=kernel63/VITIS_LOOP_856_1  
syn.directive.loop_flatten=control/VITIS_LOOP_881_2  
syn.directive.loop_flatten=control/VITIS_LOOP_880_1  
syn.directive.loop_flatten=kernel67/VITIS_LOOP_912_2  
syn.directive.loop_flatten=kernel67/VITIS_LOOP_911_1  
syn.directive.loop_flatten=kernel69/VITIS_LOOP_940_1  
syn.directive.loop_flatten=kernel70/VITIS_LOOP_955_1  
syn.directive.loop_flatten=kernel71/VITIS_LOOP_973_1  
syn.directive.loop_flatten=kernel72/VITIS_LOOP_992_1  
syn.directive.loop_flatten=kernel73/VITIS_LOOP_1011_1  
syn.directive.loop_flatten=kernel75/VITIS_LOOP_1027_1  
syn.directive.loop_flatten=kernel77/VITIS_LOOP_1043_1  
syn.directive.loop_flatten=kernel78/VITIS_LOOP_1061_1  
syn.directive.loop_flatten=kernel83/VITIS_LOOP_1080_2 off
syn.directive.loop_flatten=control/VITIS_LOOP_1102_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1101_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1119_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1118_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1136_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1135_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1151_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1150_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1171_4 off
syn.directive.loop_flatten=control/VITIS_LOOP_1172_5  
syn.directive.loop_flatten=control/VITIS_LOOP_1197_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1196_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1214_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1213_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1232_4  
syn.directive.loop_flatten=control/VITIS_LOOP_1231_3  
syn.directive.loop_flatten=control/VITIS_LOOP_1230_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1229_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1253_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1252_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1268_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1267_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1283_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1282_1  
syn.directive.loop_flatten=kernel531/VITIS_LOOP_1298_2  
syn.directive.loop_flatten=kernel531/VITIS_LOOP_1297_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1315_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1314_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1335_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1334_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1356_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1355_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1377_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1376_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1395_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1394_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1413_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1412_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1433_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1432_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1455_4 off
syn.directive.loop_flatten=control/VITIS_LOOP_1456_5  
syn.directive.loop_flatten=control/VITIS_LOOP_1485_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1484_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1502_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1501_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1519_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1518_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1537_4  
syn.directive.loop_flatten=control/VITIS_LOOP_1536_3  
syn.directive.loop_flatten=control/VITIS_LOOP_1535_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1534_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1558_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1557_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1573_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1572_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1590_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1589_1  
syn.directive.loop_flatten=kernel553/VITIS_LOOP_1605_2  
syn.directive.loop_flatten=kernel553/VITIS_LOOP_1604_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1622_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1621_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1642_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1641_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1663_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1662_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1684_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1683_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1702_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1701_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1720_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1719_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1740_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1739_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1762_4 off
syn.directive.loop_flatten=control/VITIS_LOOP_1763_5  
syn.directive.loop_flatten=control/VITIS_LOOP_1792_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1791_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1809_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1808_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1826_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1825_1  
syn.directive.loop_flatten=kernel571/VITIS_LOOP_1841_2  
syn.directive.loop_flatten=kernel571/VITIS_LOOP_1840_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1858_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1857_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1878_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1877_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1899_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1898_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1920_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1919_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1938_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1937_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1956_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1955_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1976_2  
syn.directive.loop_flatten=control/VITIS_LOOP_1975_1  
syn.directive.loop_flatten=control/VITIS_LOOP_1998_4 off
syn.directive.loop_flatten=control/VITIS_LOOP_1999_5  
syn.directive.loop_flatten=control/VITIS_LOOP_2028_2  
syn.directive.loop_flatten=control/VITIS_LOOP_2027_1  
syn.directive.loop_flatten=control/VITIS_LOOP_2045_2  
syn.directive.loop_flatten=control/VITIS_LOOP_2044_1  
syn.directive.loop_flatten=control/VITIS_LOOP_2062_2  
syn.directive.loop_flatten=control/VITIS_LOOP_2061_1  
syn.directive.loop_flatten=kernel589/VITIS_LOOP_2077_2  
syn.directive.loop_flatten=kernel589/VITIS_LOOP_2076_1  
syn.directive.loop_flatten=control/VITIS_LOOP_2094_2  
syn.directive.loop_flatten=control/VITIS_LOOP_2093_1  
syn.directive.loop_flatten=control/VITIS_LOOP_2114_2  
syn.directive.loop_flatten=control/VITIS_LOOP_2113_1  
syn.directive.loop_flatten=control/VITIS_LOOP_2135_2  
syn.directive.loop_flatten=control/VITIS_LOOP_2134_1  
syn.directive.loop_flatten=control/VITIS_LOOP_2156_2  
syn.directive.loop_flatten=control/VITIS_LOOP_2155_1  
syn.directive.loop_flatten=control/VITIS_LOOP_2174_2  
syn.directive.loop_flatten=control/VITIS_LOOP_2173_1  
syn.directive.loop_flatten=control/VITIS_LOOP_2192_2  
syn.directive.loop_flatten=control/VITIS_LOOP_2191_1  
syn.directive.loop_flatten=control/VITIS_LOOP_2212_2  
syn.directive.loop_flatten=control/VITIS_LOOP_2211_1  
syn.directive.loop_flatten=control/VITIS_LOOP_2237_5  
syn.directive.loop_flatten=control/VITIS_LOOP_2236_4  
syn.directive.loop_flatten=control/VITIS_LOOP_2235_3  
syn.directive.loop_flatten=control/VITIS_LOOP_2234_2  
syn.directive.loop_flatten=control/VITIS_LOOP_2233_1  
syn.directive.loop_flatten=control/VITIS_LOOP_2266_2  
syn.directive.loop_flatten=control/VITIS_LOOP_2265_1  
syn.directive.loop_flatten=control/VITIS_LOOP_2283_2  
syn.directive.loop_flatten=control/VITIS_LOOP_2282_1  
syn.directive.loop_flatten=control/VITIS_LOOP_2300_2  
syn.directive.loop_flatten=control/VITIS_LOOP_2299_1  


