// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module control_control_Pipeline_VITIS_LOOP_1534_1_VITIS_LOOP_1535_2_VITIS_LOOP_1536_3_VITIS_LOO (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_g0_0_AWVALID,
        m_axi_g0_0_AWREADY,
        m_axi_g0_0_AWADDR,
        m_axi_g0_0_AWID,
        m_axi_g0_0_AWLEN,
        m_axi_g0_0_AWSIZE,
        m_axi_g0_0_AWBURST,
        m_axi_g0_0_AWLOCK,
        m_axi_g0_0_AWCACHE,
        m_axi_g0_0_AWPROT,
        m_axi_g0_0_AWQOS,
        m_axi_g0_0_AWREGION,
        m_axi_g0_0_AWUSER,
        m_axi_g0_0_WVALID,
        m_axi_g0_0_WREADY,
        m_axi_g0_0_WDATA,
        m_axi_g0_0_WSTRB,
        m_axi_g0_0_WLAST,
        m_axi_g0_0_WID,
        m_axi_g0_0_WUSER,
        m_axi_g0_0_ARVALID,
        m_axi_g0_0_ARREADY,
        m_axi_g0_0_ARADDR,
        m_axi_g0_0_ARID,
        m_axi_g0_0_ARLEN,
        m_axi_g0_0_ARSIZE,
        m_axi_g0_0_ARBURST,
        m_axi_g0_0_ARLOCK,
        m_axi_g0_0_ARCACHE,
        m_axi_g0_0_ARPROT,
        m_axi_g0_0_ARQOS,
        m_axi_g0_0_ARREGION,
        m_axi_g0_0_ARUSER,
        m_axi_g0_0_RVALID,
        m_axi_g0_0_RREADY,
        m_axi_g0_0_RDATA,
        m_axi_g0_0_RLAST,
        m_axi_g0_0_RID,
        m_axi_g0_0_RFIFONUM,
        m_axi_g0_0_RUSER,
        m_axi_g0_0_RRESP,
        m_axi_g0_0_BVALID,
        m_axi_g0_0_BREADY,
        m_axi_g0_0_BRESP,
        m_axi_g0_0_BID,
        m_axi_g0_0_BUSER,
        sext_ln2299,
        sext_ln2265,
        v1159,
        v949,
        grp_fu_7597_p_din0,
        grp_fu_7597_p_din1,
        grp_fu_7597_p_opcode,
        grp_fu_7597_p_dout0,
        grp_fu_7597_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_g0_0_AWVALID;
input   m_axi_g0_0_AWREADY;
output  [63:0] m_axi_g0_0_AWADDR;
output  [0:0] m_axi_g0_0_AWID;
output  [31:0] m_axi_g0_0_AWLEN;
output  [2:0] m_axi_g0_0_AWSIZE;
output  [1:0] m_axi_g0_0_AWBURST;
output  [1:0] m_axi_g0_0_AWLOCK;
output  [3:0] m_axi_g0_0_AWCACHE;
output  [2:0] m_axi_g0_0_AWPROT;
output  [3:0] m_axi_g0_0_AWQOS;
output  [3:0] m_axi_g0_0_AWREGION;
output  [0:0] m_axi_g0_0_AWUSER;
output   m_axi_g0_0_WVALID;
input   m_axi_g0_0_WREADY;
output  [31:0] m_axi_g0_0_WDATA;
output  [3:0] m_axi_g0_0_WSTRB;
output   m_axi_g0_0_WLAST;
output  [0:0] m_axi_g0_0_WID;
output  [0:0] m_axi_g0_0_WUSER;
output   m_axi_g0_0_ARVALID;
input   m_axi_g0_0_ARREADY;
output  [63:0] m_axi_g0_0_ARADDR;
output  [0:0] m_axi_g0_0_ARID;
output  [31:0] m_axi_g0_0_ARLEN;
output  [2:0] m_axi_g0_0_ARSIZE;
output  [1:0] m_axi_g0_0_ARBURST;
output  [1:0] m_axi_g0_0_ARLOCK;
output  [3:0] m_axi_g0_0_ARCACHE;
output  [2:0] m_axi_g0_0_ARPROT;
output  [3:0] m_axi_g0_0_ARQOS;
output  [3:0] m_axi_g0_0_ARREGION;
output  [0:0] m_axi_g0_0_ARUSER;
input   m_axi_g0_0_RVALID;
output   m_axi_g0_0_RREADY;
input  [31:0] m_axi_g0_0_RDATA;
input   m_axi_g0_0_RLAST;
input  [0:0] m_axi_g0_0_RID;
input  [8:0] m_axi_g0_0_RFIFONUM;
input  [0:0] m_axi_g0_0_RUSER;
input  [1:0] m_axi_g0_0_RRESP;
input   m_axi_g0_0_BVALID;
output   m_axi_g0_0_BREADY;
input  [1:0] m_axi_g0_0_BRESP;
input  [0:0] m_axi_g0_0_BID;
input  [0:0] m_axi_g0_0_BUSER;
input  [61:0] sext_ln2299;
input  [61:0] sext_ln2265;
input  [63:0] v1159;
input  [63:0] v949;
output  [31:0] grp_fu_7597_p_din0;
output  [31:0] grp_fu_7597_p_din1;
output  [4:0] grp_fu_7597_p_opcode;
input  [0:0] grp_fu_7597_p_dout0;
output   grp_fu_7597_p_ce;

reg ap_idle;
reg m_axi_g0_0_AWVALID;
reg m_axi_g0_0_WVALID;
reg m_axi_g0_0_ARVALID;
reg[63:0] m_axi_g0_0_ARADDR;
reg m_axi_g0_0_RREADY;
reg m_axi_g0_0_BREADY;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg    ap_block_pp0_stage1_subdone_grp2_done_reg;
reg    ap_block_pp0_stage1_subdone_grp2;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage1_subdone_grp4_done_reg;
reg    ap_block_pp0_stage1_subdone_grp4;
reg    ap_block_pp0_stage1_subdone_grp5_done_reg;
reg    ap_block_pp0_stage1_subdone_grp5;
reg    ap_block_pp0_stage1_subdone_grp7_done_reg;
reg    ap_block_pp0_stage1_subdone_grp7;
reg    ap_enable_reg_pp0_iter0_reg;
wire   [0:0] icmp_ln1534_fu_300_p2;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    g0_blk_n_AR;
wire    ap_block_pp0_stage0_grp1;
reg   [0:0] icmp_ln1534_reg_955;
reg    ap_block_pp0_stage0_subdone_grp1_done_reg;
reg    ap_block_pp0_stage0_subdone_grp1;
reg    ap_block_pp0_stage0_subdone;
reg    g0_blk_n_R;
wire    ap_block_pp0_stage0_grp3;
reg    ap_block_pp0_stage0_subdone_grp3_done_reg;
reg    ap_block_pp0_stage0_subdone_grp3;
wire    ap_block_pp0_stage1_grp2;
wire    ap_block_pp0_stage1_grp4;
reg    g0_blk_n_AW;
wire    ap_block_pp0_stage1_grp5;
reg    g0_blk_n_W;
wire    ap_block_pp0_stage0_grp6;
reg    ap_block_pp0_stage0_subdone_grp6_done_reg;
reg    ap_block_pp0_stage0_subdone_grp6;
reg    g0_blk_n_B;
wire    ap_block_pp0_stage1_grp7;
reg   [7:0] reg_242;
reg    ap_block_pp0_stage0_11001_grp3;
reg    ap_block_pp0_stage1_11001_grp4;
reg    ap_block_pp0_stage0_11001_grp6;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage1_11001;
wire   [7:0] select_ln1536_fu_496_p3;
reg   [7:0] select_ln1536_reg_959;
wire   [3:0] trunc_ln1542_fu_560_p1;
reg   [3:0] trunc_ln1542_reg_964;
wire   [3:0] trunc_ln1542_2_fu_606_p1;
reg   [3:0] trunc_ln1542_2_reg_969;
reg   [63:0] g0_addr_reg_974;
reg   [63:0] g0_addr_128_reg_980;
reg   [63:0] g0_addr_128_reg_980_pp0_iter2_reg;
reg   [63:0] g0_addr_128_reg_980_pp0_iter3_reg;
reg   [63:0] g0_addr_128_reg_980_pp0_iter4_reg;
reg   [63:0] g0_addr_128_reg_980_pp0_iter5_reg;
reg   [63:0] g0_addr_128_reg_980_pp0_iter6_reg;
reg   [31:0] g0_addr_read_reg_989;
wire   [22:0] trunc_ln224_1_fu_826_p1;
reg   [22:0] trunc_ln224_1_reg_994;
reg   [31:0] g0_addr_128_read_reg_999;
wire   [22:0] trunc_ln224_fu_830_p1;
reg   [22:0] trunc_ln224_reg_1004;
wire   [0:0] grp_fu_246_p2;
reg   [0:0] icmp_ln224_2_reg_1009;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
wire   [0:0] icmp_ln224_3_fu_834_p2;
reg   [0:0] icmp_ln224_3_reg_1014;
wire   [31:0] v631_fu_839_p1;
reg   [31:0] v631_reg_1019;
wire   [31:0] v632_fu_843_p1;
reg   [31:0] v632_reg_1025;
reg   [0:0] icmp_ln224_reg_1031;
wire   [0:0] icmp_ln224_1_fu_847_p2;
reg   [0:0] icmp_ln224_1_reg_1036;
wire   [31:0] v633_fu_872_p3;
reg   [31:0] v633_reg_1041;
wire  signed [63:0] sext_ln1542_fu_669_p1;
wire    ap_block_pp0_stage1;
wire  signed [63:0] sext_ln1543_fu_816_p1;
reg    ap_block_state3_io_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage1_11001_grp2;
reg    ap_block_pp0_stage1_11001_grp5;
wire    ap_block_pp0_stage0_01001_grp6;
reg    ap_block_pp0_stage1_11001_grp7;
reg   [4:0] v630_fu_136;
wire   [4:0] add_ln1538_fu_679_p2;
wire    ap_loop_init;
reg   [4:0] v629_fu_140;
wire   [4:0] select_ln1537_fu_530_p3;
reg   [9:0] indvar_flatten13447_fu_144;
wire   [9:0] select_ln1537_1_fu_691_p3;
reg   [7:0] v628_fu_148;
reg   [16:0] indvar_flatten13460_fu_152;
wire   [16:0] select_ln1536_1_fu_705_p3;
reg   [1:0] v627_fu_156;
wire   [1:0] select_ln1535_fu_444_p3;
reg   [17:0] indvar_flatten13483_fu_160;
wire   [17:0] select_ln1535_1_fu_719_p3;
reg   [1:0] v626_fu_164;
wire   [1:0] select_ln1534_1_fu_392_p3;
reg   [18:0] indvar_flatten13516_fu_168;
wire   [18:0] add_ln1534_1_fu_306_p2;
wire    ap_block_pp0_stage0_grp0;
wire    ap_block_pp0_stage1_grp0;
wire   [0:0] icmp_ln1535_fu_342_p2;
wire   [0:0] icmp_ln1537_fu_368_p2;
wire   [0:0] xor_ln1534_fu_356_p2;
wire   [0:0] icmp_ln1536_fu_380_p2;
wire   [1:0] add_ln1534_fu_336_p2;
wire   [1:0] select_ln1534_fu_348_p3;
wire   [0:0] and_ln1534_2_fu_386_p2;
wire   [0:0] empty_fu_406_p2;
wire   [0:0] exitcond_flatten13462_not_fu_420_p2;
wire   [0:0] not_exitcond_flatten13462_mid213515_fu_426_p2;
wire   [0:0] and_ln1534_1_fu_374_p2;
wire   [1:0] add_ln1535_fu_400_p2;
wire   [7:0] v628_mid213467_fu_412_p3;
wire   [0:0] exitcond_flatten13449_mid213482_fu_438_p2;
wire   [0:0] empty_109_fu_458_p2;
wire   [0:0] empty_110_fu_464_p2;
wire   [0:0] not_exitcond_flatten13449_mid213482_fu_478_p2;
wire   [0:0] and_ln1534_fu_432_p2;
wire   [0:0] icmp_ln1538_mid213478_fu_484_p2;
wire   [0:0] icmp_ln1538_fu_362_p2;
wire   [7:0] add_ln1536_fu_452_p2;
wire   [4:0] v629_mid213454_fu_470_p3;
wire   [0:0] icmp_ln1538_mid213459_fu_490_p2;
wire   [0:0] empty_111_fu_510_p2;
wire   [0:0] empty_112_fu_516_p2;
wire   [4:0] add_ln1537_fu_504_p2;
wire   [7:0] mul_ln1542_fu_550_p0;
wire   [13:0] mul_ln1542_fu_550_p1;
wire   [20:0] mul_ln1542_fu_550_p2;
wire   [4:0] shl_ln1542_fu_564_p2;
wire   [5:0] zext_ln1542_fu_570_p1;
wire   [5:0] zext_ln1534_fu_538_p1;
wire   [5:0] add_ln1542_fu_574_p2;
wire   [8:0] tmp_fu_588_p3;
wire   [12:0] p_shl_fu_580_p3;
wire   [12:0] zext_ln1543_1_fu_596_p1;
wire   [4:0] v630_mid2_fu_522_p3;
wire   [4:0] shl_ln1542_1_fu_610_p2;
wire   [5:0] zext_ln1542_1_fu_616_p1;
wire   [5:0] zext_ln1536_fu_542_p1;
wire   [5:0] add_ln1542_1_fu_620_p2;
wire   [7:0] shl_ln1542_2_fu_626_p3;
wire   [63:0] zext_ln1543_fu_556_p1;
wire   [12:0] add_ln1543_2_fu_600_p2;
wire   [12:0] zext_ln1542_2_fu_634_p1;
wire   [12:0] add_ln1542_3_fu_643_p2;
wire   [63:0] zext_ln1542_3_fu_649_p1;
wire   [63:0] add_ln1542_2_fu_638_p2;
wire   [63:0] add_ln1542_4_fu_653_p2;
wire   [61:0] trunc_ln1542_1_fu_659_p4;
wire   [9:0] add_ln1537_1_fu_685_p2;
wire   [16:0] add_ln1536_1_fu_699_p2;
wire   [17:0] add_ln1535_1_fu_713_p2;
wire   [17:0] shl_ln_fu_772_p3;
wire   [63:0] zext_ln1537_fu_779_p1;
wire   [9:0] tmp35_fu_788_p4;
wire   [63:0] zext_ln1543_2_fu_796_p1;
wire   [63:0] add_ln1543_fu_783_p2;
wire   [63:0] add_ln1543_1_fu_800_p2;
wire   [61:0] trunc_ln_fu_806_p4;
wire   [0:0] or_ln224_fu_852_p2;
wire   [0:0] or_ln224_1_fu_856_p2;
wire   [0:0] and_ln224_fu_860_p2;
wire   [0:0] and_ln224_1_fu_866_p2;
reg    grp_fu_228_ce;
reg    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage0_00001_grp0;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [1:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [20:0] mul_ln1542_fu_550_p00;
reg    ap_condition_906;
reg    ap_condition_910;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp2_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp4_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp5_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp7_done_reg = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp1_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp3_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp6_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 v630_fu_136 = 5'd0;
#0 v629_fu_140 = 5'd0;
#0 indvar_flatten13447_fu_144 = 10'd0;
#0 v628_fu_148 = 8'd0;
#0 indvar_flatten13460_fu_152 = 17'd0;
#0 v627_fu_156 = 2'd0;
#0 indvar_flatten13483_fu_160 = 18'd0;
#0 v626_fu_164 = 2'd0;
#0 indvar_flatten13516_fu_168 = 19'd0;
#0 ap_done_reg = 1'b0;
end

control_mul_8ns_14ns_21_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 21 ))
mul_8ns_14ns_21_1_1_U246(
    .din0(mul_ln1542_fu_550_p0),
    .din1(mul_ln1542_fu_550_p1),
    .dout(mul_ln1542_fu_550_p2)
);

control_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp1)) begin
                ap_block_pp0_stage0_subdone_grp1_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp3)) begin
                ap_block_pp0_stage0_subdone_grp3_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp6_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp6_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp6)) begin
                ap_block_pp0_stage0_subdone_grp6_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp2)) begin
                ap_block_pp0_stage1_subdone_grp2_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp4_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp4_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp4)) begin
                ap_block_pp0_stage1_subdone_grp4_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp5_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp5_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp5)) begin
                ap_block_pp0_stage1_subdone_grp5_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp7_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp7_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp7)) begin
                ap_block_pp0_stage1_subdone_grp7_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        indvar_flatten13447_fu_144 <= 10'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln1534_fu_300_p2 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        indvar_flatten13447_fu_144 <= select_ln1537_1_fu_691_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        indvar_flatten13460_fu_152 <= 17'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln1534_fu_300_p2 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        indvar_flatten13460_fu_152 <= select_ln1536_1_fu_705_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        indvar_flatten13483_fu_160 <= 18'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln1534_fu_300_p2 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        indvar_flatten13483_fu_160 <= select_ln1535_1_fu_719_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        indvar_flatten13516_fu_168 <= 19'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln1534_fu_300_p2 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        indvar_flatten13516_fu_168 <= add_ln1534_1_fu_306_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        v626_fu_164 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln1534_fu_300_p2 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        v626_fu_164 <= select_ln1534_1_fu_392_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        v627_fu_156 <= 2'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln1534_fu_300_p2 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        v627_fu_156 <= select_ln1535_fu_444_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        v628_fu_148 <= 8'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln1534_fu_300_p2 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        v628_fu_148 <= select_ln1536_fu_496_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        v629_fu_140 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln1534_fu_300_p2 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        v629_fu_140 <= select_ln1537_fu_530_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        v630_fu_136 <= 5'd0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln1534_fu_300_p2 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        v630_fu_136 <= add_ln1538_fu_679_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        g0_addr_reg_974 <= sext_ln1542_fu_669_p1;
        icmp_ln1534_reg_955 <= icmp_ln1534_fu_300_p2;
        select_ln1536_reg_959 <= select_ln1536_fu_496_p3;
        trunc_ln1542_2_reg_969 <= trunc_ln1542_2_fu_606_p1;
        trunc_ln1542_reg_964 <= trunc_ln1542_fu_560_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp4) & (1'b0 == ap_block_pp0_stage1_subdone_grp4_done_reg))) begin
        g0_addr_128_read_reg_999 <= m_axi_g0_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg))) begin
        g0_addr_128_reg_980 <= sext_ln1543_fu_816_p1;
        g0_addr_128_reg_980_pp0_iter2_reg <= g0_addr_128_reg_980;
        g0_addr_128_reg_980_pp0_iter3_reg <= g0_addr_128_reg_980_pp0_iter2_reg;
        g0_addr_128_reg_980_pp0_iter4_reg <= g0_addr_128_reg_980_pp0_iter3_reg;
        g0_addr_128_reg_980_pp0_iter5_reg <= g0_addr_128_reg_980_pp0_iter4_reg;
        g0_addr_128_reg_980_pp0_iter6_reg <= g0_addr_128_reg_980_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg))) begin
        g0_addr_read_reg_989 <= m_axi_g0_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        icmp_ln224_1_reg_1036 <= icmp_ln224_1_fu_847_p2;
        v631_reg_1019 <= v631_fu_839_p1;
        v632_reg_1025 <= v632_fu_843_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        icmp_ln224_2_reg_1009 <= grp_fu_246_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        icmp_ln224_3_reg_1014 <= icmp_ln224_3_fu_834_p2;
        v633_reg_1041 <= v633_fu_872_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        icmp_ln224_reg_1031 <= grp_fu_246_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp4) & (1'b0 == ap_block_pp0_stage1_subdone_grp4_done_reg)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)))) begin
        reg_242 <= {{m_axi_g0_0_RDATA[30:23]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg))) begin
        trunc_ln224_1_reg_994 <= trunc_ln224_1_fu_826_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp4) & (1'b0 == ap_block_pp0_stage1_subdone_grp4_done_reg))) begin
        trunc_ln224_reg_1004 <= trunc_ln224_fu_830_p1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln1534_fu_300_p2 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1534_reg_955 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg) & (1'b0 == ap_block_pp0_stage0_grp1)))) begin
        g0_blk_n_AR = m_axi_g0_0_ARREADY;
    end else begin
        g0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp5) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg))) begin
        g0_blk_n_AW = m_axi_g0_0_AWREADY;
    end else begin
        g0_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp7) & (1'b0 == ap_block_pp0_stage1_subdone_grp7_done_reg))) begin
        g0_blk_n_B = m_axi_g0_0_BVALID;
    end else begin
        g0_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp4) & (1'b0 == ap_block_pp0_stage1_subdone_grp4_done_reg)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg) & (1'b0 == ap_block_pp0_stage0_grp3)))) begin
        g0_blk_n_R = m_axi_g0_0_RVALID;
    end else begin
        g0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg) & (1'b0 == ap_block_pp0_stage0_grp6))) begin
        g0_blk_n_W = m_axi_g0_0_WREADY;
    end else begin
        g0_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)))) begin
        grp_fu_228_ce = 1'b1;
    end else begin
        grp_fu_228_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
        if ((1'b1 == ap_condition_910)) begin
            m_axi_g0_0_ARADDR = g0_addr_128_reg_980;
        end else if ((1'b1 == ap_condition_906)) begin
            m_axi_g0_0_ARADDR = g0_addr_reg_974;
        end else begin
            m_axi_g0_0_ARADDR = 'bx;
        end
    end else begin
        m_axi_g0_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1534_reg_955 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)))) begin
        m_axi_g0_0_ARVALID = 1'b1;
    end else begin
        m_axi_g0_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp5) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg))) begin
        m_axi_g0_0_AWVALID = 1'b1;
    end else begin
        m_axi_g0_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp7) & (1'b0 == ap_block_pp0_stage1_subdone_grp7_done_reg))) begin
        m_axi_g0_0_BREADY = 1'b1;
    end else begin
        m_axi_g0_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp4) & (1'b0 == ap_block_pp0_stage1_subdone_grp4_done_reg)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp3) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)))) begin
        m_axi_g0_0_RREADY = 1'b1;
    end else begin
        m_axi_g0_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp6) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg))) begin
        m_axi_g0_0_WVALID = 1'b1;
    end else begin
        m_axi_g0_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1534_1_fu_306_p2 = (indvar_flatten13516_fu_168 + 19'd1);

assign add_ln1534_fu_336_p2 = (v626_fu_164 + 2'd1);

assign add_ln1535_1_fu_713_p2 = (indvar_flatten13483_fu_160 + 18'd1);

assign add_ln1535_fu_400_p2 = (select_ln1534_fu_348_p3 + 2'd1);

assign add_ln1536_1_fu_699_p2 = (indvar_flatten13460_fu_152 + 17'd1);

assign add_ln1536_fu_452_p2 = (v628_mid213467_fu_412_p3 + 8'd1);

assign add_ln1537_1_fu_685_p2 = (indvar_flatten13447_fu_144 + 10'd1);

assign add_ln1537_fu_504_p2 = (v629_mid213454_fu_470_p3 + 5'd1);

assign add_ln1538_fu_679_p2 = (v630_mid2_fu_522_p3 + 5'd1);

assign add_ln1542_1_fu_620_p2 = (zext_ln1542_1_fu_616_p1 + zext_ln1536_fu_542_p1);

assign add_ln1542_2_fu_638_p2 = (zext_ln1543_fu_556_p1 + v1159);

assign add_ln1542_3_fu_643_p2 = (add_ln1543_2_fu_600_p2 + zext_ln1542_2_fu_634_p1);

assign add_ln1542_4_fu_653_p2 = (zext_ln1542_3_fu_649_p1 + add_ln1542_2_fu_638_p2);

assign add_ln1542_fu_574_p2 = (zext_ln1542_fu_570_p1 + zext_ln1534_fu_538_p1);

assign add_ln1543_1_fu_800_p2 = (zext_ln1543_2_fu_796_p1 + add_ln1543_fu_783_p2);

assign add_ln1543_2_fu_600_p2 = (p_shl_fu_580_p3 + zext_ln1543_1_fu_596_p1);

assign add_ln1543_fu_783_p2 = (zext_ln1537_fu_779_p1 + v949);

assign and_ln1534_1_fu_374_p2 = (xor_ln1534_fu_356_p2 & icmp_ln1537_fu_368_p2);

assign and_ln1534_2_fu_386_p2 = (xor_ln1534_fu_356_p2 & icmp_ln1536_fu_380_p2);

assign and_ln1534_fu_432_p2 = (xor_ln1534_fu_356_p2 & not_exitcond_flatten13462_mid213515_fu_426_p2);

assign and_ln224_1_fu_866_p2 = (grp_fu_7597_p_dout0 & and_ln224_fu_860_p2);

assign and_ln224_fu_860_p2 = (or_ln224_fu_852_p2 & or_ln224_1_fu_856_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0_00001_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001_grp6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((m_axi_g0_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg)) | ((m_axi_g0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp3 = ((m_axi_g0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp6 = ((m_axi_g0_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((m_axi_g0_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg)) | ((m_axi_g0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state3_io_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp3 = ((m_axi_g0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp3_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone_grp6 = ((m_axi_g0_0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone_grp6_done_reg));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp7_done_reg) & (m_axi_g0_0_BVALID == 1'b0)) | ((m_axi_g0_0_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg)) | ((m_axi_g0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp4_done_reg)) | ((m_axi_g0_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg)));
end

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp2 = ((m_axi_g0_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp4 = ((m_axi_g0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp4_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp5 = ((m_axi_g0_0_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_11001_grp7 = ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp7_done_reg) & (m_axi_g0_0_BVALID == 1'b0));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp7_done_reg) & (m_axi_g0_0_BVALID == 1'b0)) | ((m_axi_g0_0_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg)) | ((m_axi_g0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp4_done_reg)) | ((m_axi_g0_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg)));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp2 = ((m_axi_g0_0_ARREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp4 = ((m_axi_g0_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp4_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp5 = ((m_axi_g0_0_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp5_done_reg));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone_grp7 = ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone_grp7_done_reg) & (m_axi_g0_0_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state3_io_grp1 = ((m_axi_g0_0_ARREADY == 1'b0) & (icmp_ln1534_reg_955 == 1'd0));
end

always @ (*) begin
    ap_condition_906 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1534_reg_955 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b0 == ap_block_pp0_stage0_subdone_grp1_done_reg));
end

always @ (*) begin
    ap_condition_910 = ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp2) & (1'b0 == ap_block_pp0_stage1_subdone_grp2_done_reg));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign empty_109_fu_458_p2 = (exitcond_flatten13449_mid213482_fu_438_p2 | and_ln1534_2_fu_386_p2);

assign empty_110_fu_464_p2 = (icmp_ln1535_fu_342_p2 | empty_109_fu_458_p2);

assign empty_111_fu_510_p2 = (icmp_ln1538_mid213459_fu_490_p2 | exitcond_flatten13449_mid213482_fu_438_p2);

assign empty_112_fu_516_p2 = (empty_fu_406_p2 | empty_111_fu_510_p2);

assign empty_fu_406_p2 = (icmp_ln1535_fu_342_p2 | and_ln1534_2_fu_386_p2);

assign exitcond_flatten13449_mid213482_fu_438_p2 = (not_exitcond_flatten13462_mid213515_fu_426_p2 & and_ln1534_1_fu_374_p2);

assign exitcond_flatten13462_not_fu_420_p2 = (icmp_ln1536_fu_380_p2 ^ 1'd1);

assign grp_fu_246_p2 = ((reg_242 != 8'd255) ? 1'b1 : 1'b0);

assign grp_fu_7597_p_ce = grp_fu_228_ce;

assign grp_fu_7597_p_din0 = v632_fu_843_p1;

assign grp_fu_7597_p_din1 = v631_fu_839_p1;

assign grp_fu_7597_p_opcode = 5'd4;

assign icmp_ln1534_fu_300_p2 = ((indvar_flatten13516_fu_168 == 19'd442368) ? 1'b1 : 1'b0);

assign icmp_ln1535_fu_342_p2 = ((indvar_flatten13483_fu_160 == 18'd147456) ? 1'b1 : 1'b0);

assign icmp_ln1536_fu_380_p2 = ((indvar_flatten13460_fu_152 == 17'd49152) ? 1'b1 : 1'b0);

assign icmp_ln1537_fu_368_p2 = ((indvar_flatten13447_fu_144 == 10'd256) ? 1'b1 : 1'b0);

assign icmp_ln1538_fu_362_p2 = ((v630_fu_136 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln1538_mid213459_fu_490_p2 = (icmp_ln1538_mid213478_fu_484_p2 & icmp_ln1538_fu_362_p2);

assign icmp_ln1538_mid213478_fu_484_p2 = (not_exitcond_flatten13449_mid213482_fu_478_p2 & and_ln1534_fu_432_p2);

assign icmp_ln224_1_fu_847_p2 = ((trunc_ln224_reg_1004 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln224_3_fu_834_p2 = ((trunc_ln224_1_reg_994 == 23'd0) ? 1'b1 : 1'b0);

assign m_axi_g0_0_ARBURST = 2'd0;

assign m_axi_g0_0_ARCACHE = 4'd0;

assign m_axi_g0_0_ARID = 1'd0;

assign m_axi_g0_0_ARLEN = 64'd1;

assign m_axi_g0_0_ARLOCK = 2'd0;

assign m_axi_g0_0_ARPROT = 3'd0;

assign m_axi_g0_0_ARQOS = 4'd0;

assign m_axi_g0_0_ARREGION = 4'd0;

assign m_axi_g0_0_ARSIZE = 3'd0;

assign m_axi_g0_0_ARUSER = 1'd0;

assign m_axi_g0_0_AWADDR = g0_addr_128_reg_980_pp0_iter6_reg;

assign m_axi_g0_0_AWBURST = 2'd0;

assign m_axi_g0_0_AWCACHE = 4'd0;

assign m_axi_g0_0_AWID = 1'd0;

assign m_axi_g0_0_AWLEN = 64'd1;

assign m_axi_g0_0_AWLOCK = 2'd0;

assign m_axi_g0_0_AWPROT = 3'd0;

assign m_axi_g0_0_AWQOS = 4'd0;

assign m_axi_g0_0_AWREGION = 4'd0;

assign m_axi_g0_0_AWSIZE = 3'd0;

assign m_axi_g0_0_AWUSER = 1'd0;

assign m_axi_g0_0_WDATA = v633_reg_1041;

assign m_axi_g0_0_WID = 1'd0;

assign m_axi_g0_0_WLAST = 1'b0;

assign m_axi_g0_0_WSTRB = 4'd15;

assign m_axi_g0_0_WUSER = 1'd0;

assign mul_ln1542_fu_550_p0 = mul_ln1542_fu_550_p00;

assign mul_ln1542_fu_550_p00 = select_ln1536_fu_496_p3;

assign mul_ln1542_fu_550_p1 = 21'd4624;

assign not_exitcond_flatten13449_mid213482_fu_478_p2 = (exitcond_flatten13449_mid213482_fu_438_p2 ^ 1'd1);

assign not_exitcond_flatten13462_mid213515_fu_426_p2 = (icmp_ln1535_fu_342_p2 | exitcond_flatten13462_not_fu_420_p2);

assign or_ln224_1_fu_856_p2 = (icmp_ln224_3_reg_1014 | icmp_ln224_2_reg_1009);

assign or_ln224_fu_852_p2 = (icmp_ln224_reg_1031 | icmp_ln224_1_reg_1036);

assign p_shl_fu_580_p3 = {{add_ln1542_fu_574_p2}, {7'd0}};

assign select_ln1534_1_fu_392_p3 = ((icmp_ln1535_fu_342_p2[0:0] == 1'b1) ? add_ln1534_fu_336_p2 : v626_fu_164);

assign select_ln1534_fu_348_p3 = ((icmp_ln1535_fu_342_p2[0:0] == 1'b1) ? 2'd0 : v627_fu_156);

assign select_ln1535_1_fu_719_p3 = ((icmp_ln1535_fu_342_p2[0:0] == 1'b1) ? 18'd1 : add_ln1535_1_fu_713_p2);

assign select_ln1535_fu_444_p3 = ((and_ln1534_2_fu_386_p2[0:0] == 1'b1) ? add_ln1535_fu_400_p2 : select_ln1534_fu_348_p3);

assign select_ln1536_1_fu_705_p3 = ((empty_fu_406_p2[0:0] == 1'b1) ? 17'd1 : add_ln1536_1_fu_699_p2);

assign select_ln1536_fu_496_p3 = ((exitcond_flatten13449_mid213482_fu_438_p2[0:0] == 1'b1) ? add_ln1536_fu_452_p2 : v628_mid213467_fu_412_p3);

assign select_ln1537_1_fu_691_p3 = ((empty_110_fu_464_p2[0:0] == 1'b1) ? 10'd1 : add_ln1537_1_fu_685_p2);

assign select_ln1537_fu_530_p3 = ((icmp_ln1538_mid213459_fu_490_p2[0:0] == 1'b1) ? add_ln1537_fu_504_p2 : v629_mid213454_fu_470_p3);

assign sext_ln1542_fu_669_p1 = $signed(trunc_ln1542_1_fu_659_p4);

assign sext_ln1543_fu_816_p1 = $signed(trunc_ln_fu_806_p4);

assign shl_ln1542_1_fu_610_p2 = v630_mid2_fu_522_p3 << 5'd1;

assign shl_ln1542_2_fu_626_p3 = {{add_ln1542_1_fu_620_p2}, {2'd0}};

assign shl_ln1542_fu_564_p2 = select_ln1537_fu_530_p3 << 5'd1;

assign shl_ln_fu_772_p3 = {{select_ln1536_reg_959}, {10'd0}};

assign tmp35_fu_788_p4 = {{{trunc_ln1542_reg_964}, {trunc_ln1542_2_reg_969}}, {2'd0}};

assign tmp_fu_588_p3 = {{add_ln1542_fu_574_p2}, {3'd0}};

assign trunc_ln1542_1_fu_659_p4 = {{add_ln1542_4_fu_653_p2[63:2]}};

assign trunc_ln1542_2_fu_606_p1 = v630_mid2_fu_522_p3[3:0];

assign trunc_ln1542_fu_560_p1 = select_ln1537_fu_530_p3[3:0];

assign trunc_ln224_1_fu_826_p1 = m_axi_g0_0_RDATA[22:0];

assign trunc_ln224_fu_830_p1 = m_axi_g0_0_RDATA[22:0];

assign trunc_ln_fu_806_p4 = {{add_ln1543_1_fu_800_p2[63:2]}};

assign v628_mid213467_fu_412_p3 = ((empty_fu_406_p2[0:0] == 1'b1) ? 8'd0 : v628_fu_148);

assign v629_mid213454_fu_470_p3 = ((empty_110_fu_464_p2[0:0] == 1'b1) ? 5'd0 : v629_fu_140);

assign v630_mid2_fu_522_p3 = ((empty_112_fu_516_p2[0:0] == 1'b1) ? 5'd0 : v630_fu_136);

assign v631_fu_839_p1 = g0_addr_read_reg_989;

assign v632_fu_843_p1 = g0_addr_128_read_reg_999;

assign v633_fu_872_p3 = ((and_ln224_1_fu_866_p2[0:0] == 1'b1) ? v631_reg_1019 : v632_reg_1025);

assign xor_ln1534_fu_356_p2 = (icmp_ln1535_fu_342_p2 ^ 1'd1);

assign zext_ln1534_fu_538_p1 = select_ln1534_1_fu_392_p3;

assign zext_ln1536_fu_542_p1 = select_ln1535_fu_444_p3;

assign zext_ln1537_fu_779_p1 = shl_ln_fu_772_p3;

assign zext_ln1542_1_fu_616_p1 = shl_ln1542_1_fu_610_p2;

assign zext_ln1542_2_fu_634_p1 = shl_ln1542_2_fu_626_p3;

assign zext_ln1542_3_fu_649_p1 = add_ln1542_3_fu_643_p2;

assign zext_ln1542_fu_570_p1 = shl_ln1542_fu_564_p2;

assign zext_ln1543_1_fu_596_p1 = tmp_fu_588_p3;

assign zext_ln1543_2_fu_796_p1 = tmp35_fu_788_p4;

assign zext_ln1543_fu_556_p1 = mul_ln1542_fu_550_p2;

endmodule //control_control_Pipeline_VITIS_LOOP_1534_1_VITIS_LOOP_1535_2_VITIS_LOOP_1536_3_VITIS_LOO
