#include <ap_int.h>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <cmath>
#include <algorithm>

// AUTO-GENERATED by FHCA_main/tools/gen_vitis_tb.py — 请勿手工编辑。
// 重新生成: python tools/gen_vitis_tb.py --output-dir /home/hwx/HCA/FPGA-SNN/FastHCA/gen-mlir2hls/cognisnn/output \\
//   --t 5 --num-classes 11 --input-shape 2,128,128 --num-images 2
// hls.cpp: /home/hwx/HCA/FPGA-SNN/FastHCA/gen-mlir2hls/cognisnn/output/hls.cpp
// 权重表: /home/hwx/HCA/FPGA-SNN/FastHCA/gen-mlir2hls/cognisnn/output/gen/host/mem_init_ext.cpp（byte offset，勿再乘 4）

void control(ap_int<32>*, ap_int<32>*, ap_int<32>*);

#define DDR_SIZE      14001280    // from hls.cpp
#define NUM_CLASSES   11
#define T_STEPS       5
#define OUTPUT_OFFSET 8388608     // element offset (arg0-based), x4 = byte offset
#define INPUT_OFFSET  0      // element offset (arg0-based)
#define INPUT_SIZE    (5*(2*128*128))

struct WeightInfo {
    const char* filename;
    size_t byte_offset;
    size_t byte_size;
};

// 24 weight entries from gen/host/mem_init_ext.cpp
WeightInfo WEIGHTS[] = {
    {"data/const_41.bin", 55120384, 4},
    {"data/const_40.bin", 55157248, 4},
    {"data/const_39.bin", 55194112, 4},
    {"data/const_34.bin", 55230976, 4},
    {"data/const_33.bin", 55267840, 4},
    {"data/const_47.bin", 55304704, 44},
    {"data/const_46.bin", 55341568, 1408},
    {"data/const_45.bin", 55378432, 36864},
    {"data/const_44.bin", 55415296, 36864},
    {"data/const_43.bin", 55452160, 36864},
    {"data/const_42.bin", 55489024, 36864},
    {"data/const_38.bin", 55525888, 36864},
    {"data/const_37.bin", 55562752, 36864},
    {"data/const_36.bin", 55599616, 36864},
    {"data/const_35.bin", 55636480, 36864},
    {"data/const_32.bin", 55673344, 36864},
    {"data/const_31.bin", 55710208, 36864},
    {"data/const_30.bin", 55747072, 36864},
    {"data/const_29.bin", 55783936, 36864},
    {"data/const_27.bin", 55820800, 36864},
    {"data/const_26.bin", 55857664, 36864},
    {"data/const_24.bin", 55894528, 128},
    {"data/const_25.bin", 55931392, 2304},
    {"data/const_28.bin", 55968256, 4},
};

const int NUM_WEIGHTS = 24;
const int NUM_IMAGES = 2;

int main() {
    printf("============================================================\n");
    printf("cognisnn C-Simulation (T=%d)\n", T_STEPS);
    printf("============================================================\n");
    printf("DDR_SIZE = %d elements (%.1f MB)\n", DDR_SIZE, DDR_SIZE * 4.0 / 1024 / 1024);
    printf("Weights = %d files\n\n", NUM_WEIGHTS);

    ap_int<32>* ddr = (ap_int<32>*)malloc(DDR_SIZE * sizeof(ap_int<32>));
    float* input_buf = (float*)malloc(INPUT_SIZE * sizeof(float));
    if (!ddr || !input_buf) { printf("FATAL: malloc failed\n"); return 1; }

    int correct = 0;
    int hls_pt_match = 0;
    float total_l2 = 0.0f;

    for (int idx = 0; idx < NUM_IMAGES; idx++) {
        // Load true label
        char path[256];
        snprintf(path, 256, "test_images/label_%d.bin", idx);
        FILE* fp = fopen(path, "rb");
        if (!fp) { printf("FATAL: missing %s\n", path); return 1; }
        int true_label;
        fread(&true_label, sizeof(int), 1, fp);
        fclose(fp);

        // Load input image (T=5 帧连续 (per-step input))
        snprintf(path, 256, "test_images/test_image_%d.bin", idx);
        fp = fopen(path, "rb");
        if (!fp) { printf("FATAL: missing %s\n", path); return 1; }
        fread(input_buf, sizeof(float), INPUT_SIZE, fp);
        fclose(fp);

        // Load expected (PyTorch T=5, mean of per-step outputs)
        snprintf(path, 256, "test_images/expected_output_%d.bin", idx);
        float expected_output[NUM_CLASSES];
        fp = fopen(path, "rb");
        if (!fp) { printf("FATAL: missing %s\n", path); return 1; }
        fread(expected_output, sizeof(float), NUM_CLASSES, fp);
        fclose(fp);

        printf("\n--- Image %d/2 (true label=%d) ---\n", idx + 1, true_label);

        // Zero DDR (resets LIF membrane states) and load weights once
        memset(ddr, 0, DDR_SIZE * sizeof(ap_int<32>));
        for (int w = 0; w < NUM_WEIGHTS; w++) {
            fp = fopen(WEIGHTS[w].filename, "rb");
            if (!fp) { printf("FATAL: Cannot open %s\n", WEIGHTS[w].filename); return 1; }
            fread((char*)ddr + WEIGHTS[w].byte_offset, 1, WEIGHTS[w].byte_size, fp);
            fclose(fp);
        }

        // T-step loop: membrane states persist in DDR top_level buffers
        // across control() calls (mirrors spikingjelly reset_net + T-loop).
        float acc_output[NUM_CLASSES] = {0.0f};
        for (int t = 0; t < T_STEPS; t++) {
            // Reload input each step: control() may clobber the input region
            float* ddr_f = (float*)((char*)ddr + INPUT_OFFSET * sizeof(ap_int<32>));
            const float* frame = input_buf + (size_t)t * (INPUT_SIZE / T_STEPS);
            for (int i = 0; i < INPUT_SIZE / T_STEPS; i++) ddr_f[i] = frame[i];
            control(ddr, ddr, ddr);

            float* step_output = (float*)((char*)ddr + OUTPUT_OFFSET * sizeof(ap_int<32>));
            for (int i = 0; i < NUM_CLASSES; i++) acc_output[i] += step_output[i];
        }

        // spikingjelly convention: mean over T steps
        float hls_output[NUM_CLASSES];
        for (int i = 0; i < NUM_CLASSES; i++) hls_output[i] = acc_output[i] / T_STEPS;

        int hls_pred = 0;
        for (int i = 1; i < NUM_CLASSES; i++)
            if (hls_output[i] > hls_output[hls_pred]) hls_pred = i;

        // PyTorch prediction
        int pt_pred = 0;
        for (int i = 1; i < NUM_CLASSES; i++)
            if (expected_output[i] > expected_output[pt_pred]) pt_pred = i;

        // Compare HLS vs PyTorch
        float l2 = 0.0f, max_diff = 0.0f;
        for (int i = 0; i < NUM_CLASSES; i++) {
            float d = fabs(hls_output[i] - expected_output[i]);
            l2 += d * d;
            if (d > max_diff) max_diff = d;
        }
        l2 = sqrt(l2);
        total_l2 += l2;

        bool pred_correct = (hls_pred == true_label);
        if (pred_correct) correct++;
        if (hls_pred == pt_pred) hls_pt_match++;

        printf("  HLS  pred=%d, PyT pred=%d, true=%d  %s%s\n",
               hls_pred, pt_pred, true_label,
               pred_correct ? "PASS" : "FAIL",
               pred_correct && hls_pred == pt_pred ? "" : " (check)");

        // Print full output if there's disagreement
        if (l2 > 0.01f) {
            printf("  HLS out: ");
            for (int i = 0; i < NUM_CLASSES; i++) printf("%+.4f ", hls_output[i]);
            printf("\n  PyT out: ");
            for (int i = 0; i < NUM_CLASSES; i++) printf("%+.4f ", expected_output[i]);
            printf("\n");
        }
        printf("  L2=%.4f, max_diff=%.4f\n", l2, max_diff);
    }

    printf("\n============================================================\n");
    printf("RESULTS (T=%d):\n", T_STEPS);
    printf("  Accuracy:    %d/%d (%.1f%%)\n", correct, NUM_IMAGES, 100.0 * correct / NUM_IMAGES);
    printf("  HLS==PyT:    %d/%d (%.1f%%)\n", hls_pt_match, NUM_IMAGES, 100.0 * hls_pt_match / NUM_IMAGES);
    printf("  Avg L2:      %.4f\n", total_l2 / NUM_IMAGES);
    printf("============================================================\n");

    free(input_buf);
    free(ddr);
    return (correct == NUM_IMAGES && hls_pt_match == NUM_IMAGES) ? 0 : 1;
}
