#include <ap_int.h>
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <cmath>
#include <algorithm>

// AUTO-GENERATED by FHCA_main/tools/gen_vitis_tb.py — 请勿手工编辑。
// 重新生成: python tools/gen_vitis_tb.py --output-dir /home/hwx/HCA/FPGA-SNN/FastHCA/gen-mlir2hls/fashion_resnet18_spikingmlir/output \\
//   --t 4 --num-classes 10 --input-shape 1,96,96 --num-images 1
// hls.cpp: /home/hwx/HCA/FPGA-SNN/FastHCA/gen-mlir2hls/fashion_resnet18_spikingmlir/output/hls.cpp
// 权重表: /home/hwx/HCA/FPGA-SNN/FastHCA/gen-mlir2hls/fashion_resnet18_spikingmlir/output/gen/host/mem_init_ext.cpp（byte offset，勿再乘 4）

void control(ap_int<32>*, ap_int<32>*, ap_int<32>*);
void control_t(ap_int<32>*, ap_int<32>*, ap_int<32>*, const ap_int<32>*, float*, long, int, int, long);

#define DDR_SIZE      102692096    // from hls.cpp
#define NUM_CLASSES   10
#define T_STEPS       4
#define OUTPUT_OFFSET 2654208     // element offset (arg0-based), x4 = byte offset
#define INPUT_OFFSET  0      // element offset (arg0-based)
#define INPUT_SIZE    (1*96*96)

struct WeightInfo {
    const char* filename;
    size_t byte_offset;
    size_t byte_size;
};

// 42 weight entries from gen/host/mem_init_ext.cpp
WeightInfo WEIGHTS[] = {
    {"data/const_82.bin", 14406656, 20480},
    {"data/const_80.bin", 23843840, 2048},
    {"data/const_81.bin", 33281024, 9437184},
    {"data/const_78.bin", 42718208, 2048},
    {"data/const_79.bin", 52155392, 9437184},
    {"data/const_76.bin", 61592576, 2048},
    {"data/const_77.bin", 71029760, 524288},
    {"data/const_74.bin", 80466944, 2048},
    {"data/const_75.bin", 89904128, 9437184},
    {"data/const_72.bin", 99341312, 2048},
    {"data/const_73.bin", 108778496, 4718592},
    {"data/const_70.bin", 118215680, 1024},
    {"data/const_71.bin", 127652864, 2359296},
    {"data/const_68.bin", 137090048, 1024},
    {"data/const_69.bin", 146527232, 2359296},
    {"data/const_66.bin", 155964416, 1024},
    {"data/const_67.bin", 165401600, 131072},
    {"data/const_64.bin", 174838784, 1024},
    {"data/const_65.bin", 184275968, 2359296},
    {"data/const_62.bin", 193713152, 1024},
    {"data/const_63.bin", 203150336, 1179648},
    {"data/const_60.bin", 212587520, 512},
    {"data/const_61.bin", 222024704, 589824},
    {"data/const_58.bin", 231461888, 512},
    {"data/const_59.bin", 240899072, 589824},
    {"data/const_56.bin", 250336256, 512},
    {"data/const_57.bin", 259773440, 32768},
    {"data/const_54.bin", 269210624, 512},
    {"data/const_55.bin", 278647808, 589824},
    {"data/const_52.bin", 288084992, 512},
    {"data/const_53.bin", 297522176, 294912},
    {"data/const_50.bin", 306959360, 256},
    {"data/const_51.bin", 316396544, 147456},
    {"data/const_48.bin", 325833728, 256},
    {"data/const_49.bin", 335270912, 147456},
    {"data/const_46.bin", 344708096, 256},
    {"data/const_47.bin", 354145280, 147456},
    {"data/const_44.bin", 363582464, 256},
    {"data/const_45.bin", 373019648, 147456},
    {"data/const_42.bin", 382456832, 256},
    {"data/const_43.bin", 391894016, 12544},
    {"data/const_83.bin", 401331200, 40},
};

const int NUM_WEIGHTS = 42;
const int NUM_IMAGES = 1;

int main() {
    printf("============================================================\n");
    printf("fashion_resnet18 C-Simulation (T=%d)\n", T_STEPS);
    printf("============================================================\n");
    printf("DDR_SIZE = %d elements (%.1f MB)\n", DDR_SIZE, DDR_SIZE * 4.0 / 1024 / 1024);
    printf("Weights = %d files\n\n", NUM_WEIGHTS);

    ap_int<32>* ddr = (ap_int<32>*)malloc(DDR_SIZE * sizeof(ap_int<32>));
    float* input_buf = (float*)malloc(INPUT_SIZE * sizeof(float));
    
    if (!ddr || !input_buf) { printf("FATAL: malloc failed\n"); return 1; }

    int correct = 0;
    int hls_pt_match = 0;
    float total_l2 = 0.0f;

    for (int idx = 0; idx < NUM_IMAGES; idx++) {
        // Load true label
        char path[256];
        snprintf(path, 256, "test_images/label_%d.bin", idx);
        FILE* fp = fopen(path, "rb");
        if (!fp) { printf("FATAL: missing %s\n", path); return 1; }
        int true_label;
        fread(&true_label, sizeof(int), 1, fp);
        fclose(fp);

        // Load input image (单帧 (全程同一帧))
        snprintf(path, 256, "test_images/test_image_%d.bin", idx);
        fp = fopen(path, "rb");
        if (!fp) { printf("FATAL: missing %s\n", path); return 1; }
        fread(input_buf, sizeof(float), INPUT_SIZE, fp);
        fclose(fp);

        // Load expected (PyTorch T=4, mean of per-step outputs)
        snprintf(path, 256, "test_images/expected_output_%d.bin", idx);
        float expected_output[NUM_CLASSES];
        fp = fopen(path, "rb");
        if (!fp) { printf("FATAL: missing %s\n", path); return 1; }
        fread(expected_output, sizeof(float), NUM_CLASSES, fp);
        fclose(fp);

        printf("\n--- Image %d/1 (true label=%d) ---\n", idx + 1, true_label);

        // Zero DDR (resets LIF membrane states) and load weights once
        memset(ddr, 0, DDR_SIZE * sizeof(ap_int<32>));
        for (int w = 0; w < NUM_WEIGHTS; w++) {
            fp = fopen(WEIGHTS[w].filename, "rb");
            if (!fp) { printf("FATAL: Cannot open %s\n", WEIGHTS[w].filename); return 1; }
            fread((char*)ddr + WEIGHTS[w].byte_offset, 1, WEIGHTS[w].byte_size, fp);
            fclose(fp);
        }

        // T-step loop: membrane states persist in DDR top_level buffers
        // across control() calls (mirrors spikingjelly reset_net + T-loop).
        // FHCA v1.4: on-chip T-step loop via control_t() (static input)
        float* ddr_f = (float*)((char*)ddr + INPUT_OFFSET * sizeof(ap_int<32>));
        for (int i = 0; i < INPUT_SIZE; i++) ddr_f[i] = input_buf[i];

        float out_frames[T_STEPS * NUM_CLASSES];
        control_t(ddr, ddr, ddr, nullptr, out_frames,
                  OUTPUT_OFFSET, NUM_CLASSES, T_STEPS, 0);

        // spikingjelly convention: mean over T steps
        float hls_output[NUM_CLASSES] = {{0.0f}};
        for (int t = 0; t < T_STEPS; t++)
            for (int i = 0; i < NUM_CLASSES; i++)
                hls_output[i] += out_frames[t * NUM_CLASSES + i] / T_STEPS;


        int hls_pred = 0;
        for (int i = 1; i < NUM_CLASSES; i++)
            if (hls_output[i] > hls_output[hls_pred]) hls_pred = i;

        // PyTorch prediction
        int pt_pred = 0;
        for (int i = 1; i < NUM_CLASSES; i++)
            if (expected_output[i] > expected_output[pt_pred]) pt_pred = i;

        // Compare HLS vs PyTorch
        float l2 = 0.0f, max_diff = 0.0f;
        for (int i = 0; i < NUM_CLASSES; i++) {
            float d = fabs(hls_output[i] - expected_output[i]);
            l2 += d * d;
            if (d > max_diff) max_diff = d;
        }
        l2 = sqrt(l2);
        total_l2 += l2;

        bool pred_correct = (hls_pred == true_label);
        if (pred_correct) correct++;
        if (hls_pred == pt_pred) hls_pt_match++;

        printf("  HLS  pred=%d, PyT pred=%d, true=%d  %s%s\n",
               hls_pred, pt_pred, true_label,
               pred_correct ? "PASS" : "FAIL",
               pred_correct && hls_pred == pt_pred ? "" : " (check)");

        // Print full output if there's disagreement
        if (l2 > 0.01f) {
            printf("  HLS out: ");
            for (int i = 0; i < NUM_CLASSES; i++) printf("%+.4f ", hls_output[i]);
            printf("\n  PyT out: ");
            for (int i = 0; i < NUM_CLASSES; i++) printf("%+.4f ", expected_output[i]);
            printf("\n");
        }
        printf("  L2=%.4f, max_diff=%.4f\n", l2, max_diff);
    }

    printf("\n============================================================\n");
    printf("RESULTS (T=%d):\n", T_STEPS);
    printf("  Accuracy:    %d/%d (%.1f%%)\n", correct, NUM_IMAGES, 100.0 * correct / NUM_IMAGES);
    printf("  HLS==PyT:    %d/%d (%.1f%%)\n", hls_pt_match, NUM_IMAGES, 100.0 * hls_pt_match / NUM_IMAGES);
    printf("  Avg L2:      %.4f\n", total_l2 / NUM_IMAGES);
    printf("============================================================\n");

    free(input_buf);
    free(ddr);
    return (correct == NUM_IMAGES && hls_pt_match == NUM_IMAGES) ? 0 : 1;
}
