-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity control_control_Pipeline_VITIS_LOOP_1662_1_VITIS_LOOP_1663_2_VITIS_LOOP_1664_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_g0_0_AWVALID : OUT STD_LOGIC;
    m_axi_g0_0_AWREADY : IN STD_LOGIC;
    m_axi_g0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_g0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_WVALID : OUT STD_LOGIC;
    m_axi_g0_0_WREADY : IN STD_LOGIC;
    m_axi_g0_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_WLAST : OUT STD_LOGIC;
    m_axi_g0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_ARVALID : OUT STD_LOGIC;
    m_axi_g0_0_ARREADY : IN STD_LOGIC;
    m_axi_g0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_g0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_RVALID : IN STD_LOGIC;
    m_axi_g0_0_RREADY : OUT STD_LOGIC;
    m_axi_g0_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_RLAST : IN STD_LOGIC;
    m_axi_g0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_g0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_BVALID : IN STD_LOGIC;
    m_axi_g0_0_BREADY : OUT STD_LOGIC;
    m_axi_g0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln2299 : IN STD_LOGIC_VECTOR (61 downto 0);
    sext_ln2265 : IN STD_LOGIC_VECTOR (61 downto 0);
    v1159 : IN STD_LOGIC_VECTOR (63 downto 0);
    sext_ln2265_1 : IN STD_LOGIC_VECTOR (61 downto 0);
    grp_fu_7597_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_7597_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_7597_p_opcode : OUT STD_LOGIC_VECTOR (4 downto 0);
    grp_fu_7597_p_dout0 : IN STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_7597_p_ce : OUT STD_LOGIC );
end;


architecture behav of control_control_Pipeline_VITIS_LOOP_1662_1_VITIS_LOOP_1663_2_VITIS_LOOP_1664_3 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv18_30000 : STD_LOGIC_VECTOR (17 downto 0) := "110000000000000000";
    constant ap_const_lv18_1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv12_400 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv5_3 : STD_LOGIC_VECTOR (4 downto 0) := "00011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp4_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp4 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp6_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp6 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln1662_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal g0_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal icmp_ln1662_reg_569 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal g0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp3_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp3 : BOOLEAN;
    signal g0_blk_n_AW : STD_LOGIC;
    signal ap_block_pp0_stage0_grp5 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp5_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp5 : BOOLEAN;
    signal g0_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage1_grp6 : BOOLEAN;
    signal g0_blk_n_B : STD_LOGIC;
    signal ap_block_pp0_stage0_grp7 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp7_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp7 : BOOLEAN;
    signal ap_block_pp0_stage1_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_grp4 : BOOLEAN;
    signal reg_197 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001_grp3 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal sext_ln2265_1_cast_fu_201_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal sext_ln2265_1_cast_reg_564 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal icmp_ln1662_reg_569_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1662_reg_569_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1662_reg_569_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1662_reg_569_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1662_reg_569_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1662_reg_569_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1662_reg_569_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1662_1_fu_295_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1662_1_reg_573 : STD_LOGIC_VECTOR (7 downto 0);
    signal v678_mid2_fu_315_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal v678_mid2_reg_578 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln1664_fu_343_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln1664_reg_583 : STD_LOGIC_VECTOR (4 downto 0);
    signal g0_addr_reg_588 : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_reg_588_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_reg_588_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_reg_588_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_reg_588_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_reg_588_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_121_reg_597 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_s_reg_603 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln1670_fu_487_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal trunc_ln1670_reg_608 : STD_LOGIC_VECTOR (22 downto 0);
    signal v679_fu_491_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp0 : BOOLEAN;
    signal icmp_ln1670_fu_496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1670_reg_618 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1670_1_fu_501_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1670_1_reg_623 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1672_fu_516_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln1672_reg_628 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state3_io_grp1 : BOOLEAN;
    signal sext_ln1668_fu_386_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal sext_ln1669_fu_467_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp5 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp6 : BOOLEAN;
    signal ap_block_pp0_stage1_01001_grp6 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp7 : BOOLEAN;
    signal v678_fu_116 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln1664_fu_396_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal v677_fu_120 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln1663_fu_323_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten13330_fu_124 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal select_ln1663_1_fu_408_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal v676_fu_128 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal indvar_flatten13343_fu_132 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal add_ln1662_1_fu_239_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_block_pp0_stage1_grp0 : BOOLEAN;
    signal icmp_ln1663_fu_263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1664_fu_283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1662_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1662_fu_257_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1662_fu_269_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal and_ln1662_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln1663_fu_303_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln_fu_331_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln1663_fu_339_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln1668_fu_347_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_356_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln1668_fu_366_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln1668_fu_351_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln1668_1_fu_370_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln_fu_376_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal add_ln1663_1_fu_402_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp32_fu_444_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln1664_fu_441_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln1669_1_fu_456_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln1669_fu_452_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln1669_fu_461_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal or_ln1670_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal v681_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_192_ce : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage1_00001_grp0 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter8_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to7 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_695 : BOOLEAN;
    signal ap_condition_699 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component control_fcmp_32ns_32ns_1_2_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        opcode : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component control_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component control_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                        ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp3_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3)) then 
                        ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp5_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5)) then 
                        ap_block_pp0_stage0_subdone_grp5_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp7_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp7_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp7_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7)) then 
                        ap_block_pp0_stage0_subdone_grp7_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2)) then 
                        ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp4_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4)) then 
                        ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp6_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp6_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp6_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp6)) then 
                        ap_block_pp0_stage1_subdone_grp6_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to7 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter8_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to7 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter8_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to7 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter8_stage0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter4_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to7 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter8_stage0))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter5_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to7 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter8_stage0))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter6_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to7 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter8_stage0))) then 
                ap_loop_exit_ready_pp0_iter6_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter7_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to7 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter8_stage0))) then 
                ap_loop_exit_ready_pp0_iter7_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter8_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to7 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter8_stage0))) then 
                ap_loop_exit_ready_pp0_iter8_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
            end if; 
        end if;
    end process;

    indvar_flatten13330_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                indvar_flatten13330_fu_124 <= ap_const_lv12_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln1662_fu_233_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                indvar_flatten13330_fu_124 <= select_ln1663_1_fu_408_p3;
            end if; 
        end if;
    end process;

    indvar_flatten13343_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                indvar_flatten13343_fu_132 <= ap_const_lv18_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln1662_fu_233_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                indvar_flatten13343_fu_132 <= add_ln1662_1_fu_239_p2;
            end if; 
        end if;
    end process;

    v676_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                v676_fu_128 <= ap_const_lv8_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln1662_fu_233_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                v676_fu_128 <= select_ln1662_1_fu_295_p3;
            end if; 
        end if;
    end process;

    v677_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                v677_fu_120 <= ap_const_lv6_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln1662_fu_233_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                v677_fu_120 <= select_ln1663_fu_323_p3;
            end if; 
        end if;
    end process;

    v678_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                v678_fu_116 <= ap_const_lv6_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln1662_fu_233_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                v678_fu_116 <= add_ln1664_fu_396_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                g0_addr_121_reg_597 <= sext_ln1669_fu_467_p1;
                select_ln1672_reg_628 <= select_ln1672_fu_516_p3;
                sext_ln2265_1_cast_reg_564 <= sext_ln2265_1_cast_fu_201_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                g0_addr_reg_588 <= sext_ln1668_fu_386_p1;
                g0_addr_reg_588_pp0_iter1_reg <= g0_addr_reg_588;
                g0_addr_reg_588_pp0_iter2_reg <= g0_addr_reg_588_pp0_iter1_reg;
                g0_addr_reg_588_pp0_iter3_reg <= g0_addr_reg_588_pp0_iter2_reg;
                g0_addr_reg_588_pp0_iter4_reg <= g0_addr_reg_588_pp0_iter3_reg;
                g0_addr_reg_588_pp0_iter5_reg <= g0_addr_reg_588_pp0_iter4_reg;
                icmp_ln1662_reg_569 <= icmp_ln1662_fu_233_p2;
                icmp_ln1662_reg_569_pp0_iter1_reg <= icmp_ln1662_reg_569;
                icmp_ln1662_reg_569_pp0_iter2_reg <= icmp_ln1662_reg_569_pp0_iter1_reg;
                icmp_ln1662_reg_569_pp0_iter3_reg <= icmp_ln1662_reg_569_pp0_iter2_reg;
                icmp_ln1662_reg_569_pp0_iter4_reg <= icmp_ln1662_reg_569_pp0_iter3_reg;
                icmp_ln1662_reg_569_pp0_iter5_reg <= icmp_ln1662_reg_569_pp0_iter4_reg;
                icmp_ln1662_reg_569_pp0_iter6_reg <= icmp_ln1662_reg_569_pp0_iter5_reg;
                icmp_ln1662_reg_569_pp0_iter7_reg <= icmp_ln1662_reg_569_pp0_iter6_reg;
                select_ln1662_1_reg_573 <= select_ln1662_1_fu_295_p3;
                trunc_ln1664_reg_583 <= trunc_ln1664_fu_343_p1;
                v678_mid2_reg_578 <= v678_mid2_fu_315_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0))) then
                icmp_ln1670_1_reg_623 <= icmp_ln1670_1_fu_501_p2;
                icmp_ln1670_reg_618 <= icmp_ln1670_fu_496_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)))) then
                reg_197 <= m_axi_g0_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg))) then
                tmp_s_reg_603 <= m_axi_g0_0_RDATA(30 downto 23);
                trunc_ln1670_reg_608 <= trunc_ln1670_fu_487_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter8_stage0, ap_idle_pp0_0to7)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to7 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter8_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_idle_pp0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln1662_1_fu_239_p2 <= std_logic_vector(unsigned(indvar_flatten13343_fu_132) + unsigned(ap_const_lv18_1));
    add_ln1662_fu_257_p2 <= std_logic_vector(unsigned(v676_fu_128) + unsigned(ap_const_lv8_1));
    add_ln1663_1_fu_402_p2 <= std_logic_vector(unsigned(indvar_flatten13330_fu_124) + unsigned(ap_const_lv12_1));
    add_ln1663_fu_303_p2 <= std_logic_vector(unsigned(select_ln1662_fu_269_p3) + unsigned(ap_const_lv6_1));
    add_ln1664_fu_396_p2 <= std_logic_vector(unsigned(v678_mid2_fu_315_p3) + unsigned(ap_const_lv6_1));
    add_ln1668_1_fu_370_p2 <= std_logic_vector(unsigned(zext_ln1668_fu_366_p1) + unsigned(add_ln1668_fu_351_p2));
    add_ln1668_fu_351_p2 <= std_logic_vector(unsigned(zext_ln1663_fu_339_p1) + unsigned(v1159));
    add_ln1669_1_fu_456_p2 <= std_logic_vector(unsigned(zext_ln1664_fu_441_p1) + unsigned(sext_ln2265_1_cast_reg_564));
    add_ln1669_fu_461_p2 <= std_logic_vector(unsigned(add_ln1669_1_fu_456_p2) + unsigned(zext_ln1669_fu_452_p1));
    and_ln1662_fu_289_p2 <= (xor_ln1662_fu_277_p2 and icmp_ln1664_fu_283_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter9, m_axi_g0_0_AWREADY, m_axi_g0_0_RVALID, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_pp0_stage0_subdone_grp7_done_reg, ap_block_state3_io_grp1)
    begin
                ap_block_pp0_stage0_11001 <= (((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0)) or ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state3_io_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter5, m_axi_g0_0_RVALID, ap_block_pp0_stage0_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp3 <= ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp5_assign_proc : process(ap_enable_reg_pp0_iter6, m_axi_g0_0_AWREADY, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp5 <= ((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp7_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp7_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp7 <= ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter9, m_axi_g0_0_AWREADY, m_axi_g0_0_RVALID, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_pp0_stage0_subdone_grp7_done_reg, ap_block_state3_io_grp1)
    begin
                ap_block_pp0_stage0_subdone <= (((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg)) or ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0)) or ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state3_io_grp1)
    begin
                ap_block_pp0_stage0_subdone_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp3_assign_proc : process(ap_enable_reg_pp0_iter5, m_axi_g0_0_RVALID, ap_block_pp0_stage0_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp3 <= ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp5_assign_proc : process(ap_enable_reg_pp0_iter6, m_axi_g0_0_AWREADY, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp5 <= ((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp7_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp7_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp7 <= ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_00001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_01001_grp6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, m_axi_g0_0_WREADY, m_axi_g0_0_ARREADY, m_axi_g0_0_RVALID, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage1_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage1_11001 <= (((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp6_done_reg)) or ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg)) or ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg)));
    end process;

        ap_block_pp0_stage1_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_g0_0_ARREADY, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp2 <= ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage1_11001_grp4_assign_proc : process(ap_enable_reg_pp0_iter5, m_axi_g0_0_RVALID, ap_block_pp0_stage1_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp4 <= ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg));
    end process;


    ap_block_pp0_stage1_11001_grp6_assign_proc : process(ap_enable_reg_pp0_iter6, m_axi_g0_0_WREADY, ap_block_pp0_stage1_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp6 <= ((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp6_done_reg));
    end process;

        ap_block_pp0_stage1_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, m_axi_g0_0_WREADY, m_axi_g0_0_ARREADY, m_axi_g0_0_RVALID, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage1_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage1_subdone <= (((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp6_done_reg)) or ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg)) or ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg)));
    end process;

        ap_block_pp0_stage1_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_g0_0_ARREADY, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp2 <= ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage1_subdone_grp4_assign_proc : process(ap_enable_reg_pp0_iter5, m_axi_g0_0_RVALID, ap_block_pp0_stage1_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp4 <= ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg));
    end process;


    ap_block_pp0_stage1_subdone_grp6_assign_proc : process(ap_enable_reg_pp0_iter6, m_axi_g0_0_WREADY, ap_block_pp0_stage1_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp6 <= ((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp6_done_reg));
    end process;


    ap_block_state3_io_grp1_assign_proc : process(m_axi_g0_0_ARREADY, icmp_ln1662_reg_569)
    begin
                ap_block_state3_io_grp1 <= ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (icmp_ln1662_reg_569 = ap_const_lv1_0));
    end process;


    ap_condition_695_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln1662_reg_569, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
                ap_condition_695 <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1662_reg_569 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg));
    end process;


    ap_condition_699_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage1_11001_grp2)
    begin
                ap_condition_699 <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln1662_fu_233_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln1662_fu_233_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter8_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_subdone, icmp_ln1662_reg_569_pp0_iter7_reg)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (icmp_ln1662_reg_569_pp0_iter7_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter8_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter8_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to7_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to7 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to7 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_309_p2 <= (icmp_ln1663_fu_263_p2 or and_ln1662_fu_289_p2);

    g0_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, m_axi_g0_0_ARREADY, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage0_grp1, icmp_ln1662_reg_569, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage1_grp2)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1662_reg_569 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1)))) then 
            g0_blk_n_AR <= m_axi_g0_0_ARREADY;
        else 
            g0_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_AW_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter6, m_axi_g0_0_AWREADY, ap_block_pp0_stage0_grp5, ap_block_pp0_stage0_subdone_grp5_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp5))) then 
            g0_blk_n_AW <= m_axi_g0_0_AWREADY;
        else 
            g0_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_B_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter9, m_axi_g0_0_BVALID, ap_block_pp0_stage0_grp7, ap_block_pp0_stage0_subdone_grp7_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp7))) then 
            g0_blk_n_B <= m_axi_g0_0_BVALID;
        else 
            g0_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage1, m_axi_g0_0_RVALID, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage0_grp3, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage1_grp4)
    begin
        if ((((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp3)))) then 
            g0_blk_n_R <= m_axi_g0_0_RVALID;
        else 
            g0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter6, ap_CS_fsm_pp0_stage1, m_axi_g0_0_WREADY, ap_block_pp0_stage1_subdone_grp6_done_reg, ap_block_pp0_stage1_grp6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp6_done_reg))) then 
            g0_blk_n_W <= m_axi_g0_0_WREADY;
        else 
            g0_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_192_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_block_pp0_stage1_11001_grp0, ap_block_pp0_stage1_subdone_grp0_done_reg)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0)))) then 
            grp_fu_192_ce <= ap_const_logic_1;
        else 
            grp_fu_192_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_7597_p_ce <= grp_fu_192_ce;
    grp_fu_7597_p_din0 <= v679_fu_491_p1;
    grp_fu_7597_p_din1 <= ap_const_lv32_0;
    grp_fu_7597_p_opcode <= ap_const_lv5_3;
    icmp_ln1662_fu_233_p2 <= "1" when (indvar_flatten13343_fu_132 = ap_const_lv18_30000) else "0";
    icmp_ln1663_fu_263_p2 <= "1" when (indvar_flatten13330_fu_124 = ap_const_lv12_400) else "0";
    icmp_ln1664_fu_283_p2 <= "1" when (v678_fu_116 = ap_const_lv6_20) else "0";
    icmp_ln1670_1_fu_501_p2 <= "1" when (trunc_ln1670_reg_608 = ap_const_lv23_0) else "0";
    icmp_ln1670_fu_496_p2 <= "0" when (tmp_s_reg_603 = ap_const_lv8_FF) else "1";

    m_axi_g0_0_ARADDR_assign_proc : process(ap_enable_reg_pp0_iter1, g0_addr_reg_588, g0_addr_121_reg_597, ap_condition_695, ap_condition_699)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if ((ap_const_boolean_1 = ap_condition_699)) then 
                m_axi_g0_0_ARADDR <= g0_addr_121_reg_597;
            elsif ((ap_const_boolean_1 = ap_condition_695)) then 
                m_axi_g0_0_ARADDR <= g0_addr_reg_588;
            else 
                m_axi_g0_0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            m_axi_g0_0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axi_g0_0_ARBURST <= ap_const_lv2_0;
    m_axi_g0_0_ARCACHE <= ap_const_lv4_0;
    m_axi_g0_0_ARID <= ap_const_lv1_0;
    m_axi_g0_0_ARLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_g0_0_ARLOCK <= ap_const_lv2_0;
    m_axi_g0_0_ARPROT <= ap_const_lv3_0;
    m_axi_g0_0_ARQOS <= ap_const_lv4_0;
    m_axi_g0_0_ARREGION <= ap_const_lv4_0;
    m_axi_g0_0_ARSIZE <= ap_const_lv3_0;
    m_axi_g0_0_ARUSER <= ap_const_lv1_0;

    m_axi_g0_0_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp2_done_reg, icmp_ln1662_reg_569, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1, ap_block_pp0_stage1_11001_grp2)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1662_reg_569 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)))) then 
            m_axi_g0_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_g0_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_g0_0_AWADDR <= g0_addr_reg_588_pp0_iter5_reg;
    m_axi_g0_0_AWBURST <= ap_const_lv2_0;
    m_axi_g0_0_AWCACHE <= ap_const_lv4_0;
    m_axi_g0_0_AWID <= ap_const_lv1_0;
    m_axi_g0_0_AWLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_g0_0_AWLOCK <= ap_const_lv2_0;
    m_axi_g0_0_AWPROT <= ap_const_lv3_0;
    m_axi_g0_0_AWQOS <= ap_const_lv4_0;
    m_axi_g0_0_AWREGION <= ap_const_lv4_0;
    m_axi_g0_0_AWSIZE <= ap_const_lv3_0;
    m_axi_g0_0_AWUSER <= ap_const_lv1_0;

    m_axi_g0_0_AWVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone_grp5_done_reg, ap_block_pp0_stage0_11001_grp5)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp5_done_reg))) then 
            m_axi_g0_0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_g0_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_g0_0_BREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter9, ap_block_pp0_stage0_subdone_grp7_done_reg, ap_block_pp0_stage0_11001_grp7)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp7) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp7_done_reg))) then 
            m_axi_g0_0_BREADY <= ap_const_logic_1;
        else 
            m_axi_g0_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_g0_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_11001_grp3, ap_block_pp0_stage1_11001_grp4)
    begin
        if ((((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)))) then 
            m_axi_g0_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_g0_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_g0_0_WDATA <= select_ln1672_reg_628;
    m_axi_g0_0_WID <= ap_const_lv1_0;
    m_axi_g0_0_WLAST <= ap_const_logic_0;
    m_axi_g0_0_WSTRB <= ap_const_lv4_F;
    m_axi_g0_0_WUSER <= ap_const_lv1_0;

    m_axi_g0_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter6, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp6_done_reg, ap_block_pp0_stage1_11001_grp6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp6_done_reg))) then 
            m_axi_g0_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_g0_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    or_ln1670_fu_506_p2 <= (icmp_ln1670_reg_618 or icmp_ln1670_1_reg_623);
    select_ln1662_1_fu_295_p3 <= 
        add_ln1662_fu_257_p2 when (icmp_ln1663_fu_263_p2(0) = '1') else 
        v676_fu_128;
    select_ln1662_fu_269_p3 <= 
        ap_const_lv6_0 when (icmp_ln1663_fu_263_p2(0) = '1') else 
        v677_fu_120;
    select_ln1663_1_fu_408_p3 <= 
        ap_const_lv12_1 when (icmp_ln1663_fu_263_p2(0) = '1') else 
        add_ln1663_1_fu_402_p2;
    select_ln1663_fu_323_p3 <= 
        add_ln1663_fu_303_p2 when (and_ln1662_fu_289_p2(0) = '1') else 
        select_ln1662_fu_269_p3;
    select_ln1672_fu_516_p3 <= 
        reg_197 when (v681_fu_510_p2(0) = '1') else 
        ap_const_lv32_0;
        sext_ln1668_fu_386_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_376_p4),64));

        sext_ln1669_fu_467_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln1669_fu_461_p2),64));

        sext_ln2265_1_cast_fu_201_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln2265_1),63));

    shl_ln_fu_331_p3 <= (select_ln1662_1_fu_295_p3 & ap_const_lv12_0);
    tmp32_fu_444_p4 <= ((select_ln1662_1_reg_573 & trunc_ln1664_reg_583) & ap_const_lv5_0);
    tmp_fu_356_p4 <= ((trunc_ln1664_fu_343_p1 & trunc_ln1668_fu_347_p1) & ap_const_lv2_0);
    trunc_ln1664_fu_343_p1 <= select_ln1663_fu_323_p3(5 - 1 downto 0);
    trunc_ln1668_fu_347_p1 <= v678_mid2_fu_315_p3(5 - 1 downto 0);
    trunc_ln1670_fu_487_p1 <= m_axi_g0_0_RDATA(23 - 1 downto 0);
    trunc_ln_fu_376_p4 <= add_ln1668_1_fu_370_p2(63 downto 2);
    v678_mid2_fu_315_p3 <= 
        ap_const_lv6_0 when (empty_fu_309_p2(0) = '1') else 
        v678_fu_116;
    v679_fu_491_p1 <= reg_197;
    v681_fu_510_p2 <= (or_ln1670_fu_506_p2 and grp_fu_7597_p_dout0);
    xor_ln1662_fu_277_p2 <= (icmp_ln1663_fu_263_p2 xor ap_const_lv1_1);
    zext_ln1663_fu_339_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_331_p3),64));
    zext_ln1664_fu_441_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(v678_mid2_reg_578),63));
    zext_ln1668_fu_366_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_356_p4),64));
    zext_ln1669_fu_452_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp32_fu_444_p4),63));
end behav;
