-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity control_kernel60 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_g0_0_AWVALID : OUT STD_LOGIC;
    m_axi_g0_0_AWREADY : IN STD_LOGIC;
    m_axi_g0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_g0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_WVALID : OUT STD_LOGIC;
    m_axi_g0_0_WREADY : IN STD_LOGIC;
    m_axi_g0_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_WLAST : OUT STD_LOGIC;
    m_axi_g0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_ARVALID : OUT STD_LOGIC;
    m_axi_g0_0_ARREADY : IN STD_LOGIC;
    m_axi_g0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_g0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_RVALID : IN STD_LOGIC;
    m_axi_g0_0_RREADY : OUT STD_LOGIC;
    m_axi_g0_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_RLAST : IN STD_LOGIC;
    m_axi_g0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_g0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_BVALID : IN STD_LOGIC;
    m_axi_g0_0_BREADY : OUT STD_LOGIC;
    m_axi_g0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    v320 : IN STD_LOGIC_VECTOR (63 downto 0);
    v321 : IN STD_LOGIC_VECTOR (63 downto 0);
    v322 : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of control_kernel60 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv21_180000 : STD_LOGIC_VECTOR (20 downto 0) := "110000000000000000000";
    constant ap_const_lv21_1 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv16_6000 : STD_LOGIC_VECTOR (15 downto 0) := "0110000000000000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv13_800 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal icmp_ln795_reg_734 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_io_grp1 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp5_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp5 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal g0_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage2_grp1 : BOOLEAN;
    signal g0_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_grp4 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp4_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp4 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_grp5 : BOOLEAN;
    signal ap_block_pp0_stage1_grp3 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp3_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_grp6 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp6_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp6 : BOOLEAN;
    signal g0_blk_n_AW : STD_LOGIC;
    signal g0_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage1_grp8 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp8_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp8 : BOOLEAN;
    signal g0_blk_n_B : STD_LOGIC;
    signal ap_block_pp0_stage0_grp9 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp9_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp9 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp6 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal icmp_ln795_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal icmp_ln795_reg_734_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln795_reg_734_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln795_reg_734_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln795_reg_734_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln795_reg_734_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln795_reg_734_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln796_fu_364_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln796_reg_738 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln803_fu_406_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln803_reg_744 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln803_1_fu_427_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln803_1_reg_749 : STD_LOGIC_VECTOR (5 downto 0);
    signal g0_addr_reg_754 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln804_fu_471_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln804_reg_760 : STD_LOGIC_VECTOR (4 downto 0);
    signal g0_addr_18_reg_766 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2_11001_grp5 : BOOLEAN;
    signal g0_addr_19_reg_772 : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_19_reg_772_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_19_reg_772_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_19_reg_772_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_19_reg_772_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_read_reg_781 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_11001_grp4 : BOOLEAN;
    signal g0_addr_18_read_reg_786 : STD_LOGIC_VECTOR (31 downto 0);
    signal g0_addr_19_read_reg_801 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_196_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal v331_reg_806 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp0 : BOOLEAN;
    signal grp_fu_192_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal v332_reg_816 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state4_io_grp2 : BOOLEAN;
    signal sext_ln803_fu_461_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal sext_ln804_fu_590_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln805_fu_644_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp3 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp8 : BOOLEAN;
    signal ap_block_pp0_stage1_01001_grp8 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp9 : BOOLEAN;
    signal v327_fu_114 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln798_fu_475_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal v326_fu_118 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln797_fu_398_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten_fu_122 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal select_ln797_1_fu_487_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal v325_fu_126 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal indvar_flatten12_fu_130 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal select_ln796_1_fu_501_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal v324_fu_134 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln795_1_fu_312_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten35_fu_138 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    signal add_ln795_1_fu_244_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal grp_fu_192_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal grp_fu_196_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_196_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln796_fu_274_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln797_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln795_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln795_fu_268_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln795_fu_280_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln795_1_fu_306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten_not_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten_mid234_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln795_fu_352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln798_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln796_fu_320_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal v326_mid26_fu_332_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln798_mid211_fu_358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_73_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_74_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln797_fu_372_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln_fu_410_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln804_fu_418_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp1_fu_431_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln803_fu_441_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln803_fu_422_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln803_1_fu_445_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln_fu_451_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal v327_mid2_fu_390_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln797_1_fu_481_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln796_1_fu_495_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln804_2_fu_544_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln796_fu_551_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp3_fu_560_p5 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln804_1_fu_570_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln804_fu_555_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln804_1_fu_574_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln13_fu_580_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal shl_ln2_fu_600_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln797_fu_607_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp5_fu_616_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln805_fu_624_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln805_fu_611_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln805_1_fu_628_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln14_fu_634_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_fu_192_ce : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp0 : BOOLEAN;
    signal grp_fu_196_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter7_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to6 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component control_fadd_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component control_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component control_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fadd_32ns_32ns_32_4_full_dsp_1_U509 : component control_fadd_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_192_p0,
        din1 => v331_reg_806,
        ce => grp_fu_192_ce,
        dout => grp_fu_192_p2);

    fmul_32ns_32ns_32_3_max_dsp_1_U510 : component control_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_196_p0,
        din1 => grp_fu_196_p1,
        ce => grp_fu_196_ce,
        dout => grp_fu_196_p2);

    flow_control_loop_pipe_sequential_init_U : component control_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2)) then 
                        ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp6_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp6_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp6_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6)) then 
                        ap_block_pp0_stage0_subdone_grp6_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp9_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp9_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp9_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9)) then 
                        ap_block_pp0_stage0_subdone_grp9_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp3_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp3_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp3_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3)) then 
                        ap_block_pp0_stage1_subdone_grp3_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp4_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4)) then 
                        ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp8_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp8_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp8_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp8)) then 
                        ap_block_pp0_stage1_subdone_grp8_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage2_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp1_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1)) then 
                        ap_block_pp0_stage2_subdone_grp1_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp5_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage2_subdone_grp5_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp5_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5)) then 
                        ap_block_pp0_stage2_subdone_grp5_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter4_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage0))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter5_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage0))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter6_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage0))) then 
                ap_loop_exit_ready_pp0_iter6_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter7_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage0))) then 
                ap_loop_exit_ready_pp0_iter7_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
            end if; 
        end if;
    end process;

    indvar_flatten12_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                indvar_flatten12_fu_130 <= ap_const_lv16_0;
            elsif (((icmp_ln795_fu_238_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                indvar_flatten12_fu_130 <= select_ln796_1_fu_501_p3;
            end if; 
        end if;
    end process;

    indvar_flatten35_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                indvar_flatten35_fu_138 <= ap_const_lv21_0;
            elsif (((icmp_ln795_fu_238_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                indvar_flatten35_fu_138 <= add_ln795_1_fu_244_p2;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                indvar_flatten_fu_122 <= ap_const_lv13_0;
            elsif (((icmp_ln795_fu_238_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                indvar_flatten_fu_122 <= select_ln797_1_fu_487_p3;
            end if; 
        end if;
    end process;

    v324_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                v324_fu_134 <= ap_const_lv7_0;
            elsif (((icmp_ln795_fu_238_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                v324_fu_134 <= select_ln795_1_fu_312_p3;
            end if; 
        end if;
    end process;

    v325_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                v325_fu_126 <= ap_const_lv4_0;
            elsif (((icmp_ln795_fu_238_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                v325_fu_126 <= select_ln796_fu_364_p3;
            end if; 
        end if;
    end process;

    v326_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                v326_fu_118 <= ap_const_lv7_0;
            elsif (((icmp_ln795_fu_238_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                v326_fu_118 <= select_ln797_fu_398_p3;
            end if; 
        end if;
    end process;

    v327_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                v327_fu_114 <= ap_const_lv6_0;
            elsif (((icmp_ln795_fu_238_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                v327_fu_114 <= add_ln798_fu_475_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5_done_reg))) then
                g0_addr_18_read_reg_786 <= m_axi_g0_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5_done_reg))) then
                g0_addr_18_reg_766 <= sext_ln804_fu_590_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg))) then
                g0_addr_19_read_reg_801 <= m_axi_g0_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg))) then
                g0_addr_19_reg_772 <= sext_ln805_fu_644_p1;
                g0_addr_19_reg_772_pp0_iter2_reg <= g0_addr_19_reg_772;
                g0_addr_19_reg_772_pp0_iter3_reg <= g0_addr_19_reg_772_pp0_iter2_reg;
                g0_addr_19_reg_772_pp0_iter4_reg <= g0_addr_19_reg_772_pp0_iter3_reg;
                g0_addr_19_reg_772_pp0_iter5_reg <= g0_addr_19_reg_772_pp0_iter4_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg))) then
                g0_addr_read_reg_781 <= m_axi_g0_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                g0_addr_reg_754 <= sext_ln803_fu_461_p1;
                icmp_ln795_reg_734 <= icmp_ln795_fu_238_p2;
                icmp_ln795_reg_734_pp0_iter1_reg <= icmp_ln795_reg_734;
                icmp_ln795_reg_734_pp0_iter2_reg <= icmp_ln795_reg_734_pp0_iter1_reg;
                icmp_ln795_reg_734_pp0_iter3_reg <= icmp_ln795_reg_734_pp0_iter2_reg;
                icmp_ln795_reg_734_pp0_iter4_reg <= icmp_ln795_reg_734_pp0_iter3_reg;
                icmp_ln795_reg_734_pp0_iter5_reg <= icmp_ln795_reg_734_pp0_iter4_reg;
                icmp_ln795_reg_734_pp0_iter6_reg <= icmp_ln795_reg_734_pp0_iter5_reg;
                select_ln796_reg_738 <= select_ln796_fu_364_p3;
                trunc_ln803_1_reg_749 <= trunc_ln803_1_fu_427_p1;
                trunc_ln803_reg_744 <= trunc_ln803_fu_406_p1;
                trunc_ln804_reg_760 <= trunc_ln804_fu_471_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0))) then
                v331_reg_806 <= grp_fu_196_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                v332_reg_816 <= grp_fu_192_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage2_subdone, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter7_stage0, ap_idle_pp0_0to6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_idle_pp0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln795_1_fu_244_p2 <= std_logic_vector(unsigned(indvar_flatten35_fu_138) + unsigned(ap_const_lv21_1));
    add_ln795_fu_268_p2 <= std_logic_vector(unsigned(v324_fu_134) + unsigned(ap_const_lv7_1));
    add_ln796_1_fu_495_p2 <= std_logic_vector(unsigned(indvar_flatten12_fu_130) + unsigned(ap_const_lv16_1));
    add_ln796_fu_320_p2 <= std_logic_vector(unsigned(select_ln795_fu_280_p3) + unsigned(ap_const_lv4_1));
    add_ln797_1_fu_481_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_122) + unsigned(ap_const_lv13_1));
    add_ln797_fu_372_p2 <= std_logic_vector(unsigned(v326_mid26_fu_332_p3) + unsigned(ap_const_lv7_1));
    add_ln798_fu_475_p2 <= std_logic_vector(unsigned(v327_mid2_fu_390_p3) + unsigned(ap_const_lv6_1));
    add_ln803_1_fu_445_p2 <= std_logic_vector(unsigned(zext_ln803_fu_441_p1) + unsigned(add_ln803_fu_422_p2));
    add_ln803_fu_422_p2 <= std_logic_vector(unsigned(zext_ln804_fu_418_p1) + unsigned(v320));
    add_ln804_1_fu_574_p2 <= std_logic_vector(unsigned(zext_ln804_1_fu_570_p1) + unsigned(add_ln804_fu_555_p2));
    add_ln804_fu_555_p2 <= std_logic_vector(unsigned(zext_ln796_fu_551_p1) + unsigned(v321));
    add_ln805_1_fu_628_p2 <= std_logic_vector(unsigned(zext_ln805_fu_624_p1) + unsigned(add_ln805_fu_611_p2));
    add_ln805_fu_611_p2 <= std_logic_vector(unsigned(zext_ln797_fu_607_p1) + unsigned(v322));
    and_ln795_1_fu_306_p2 <= (xor_ln795_fu_288_p2 and icmp_ln797_fu_300_p2);
    and_ln795_fu_352_p2 <= (xor_ln795_fu_288_p2 and not_exitcond_flatten_mid234_fu_346_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter8, m_axi_g0_0_AWREADY, m_axi_g0_0_RVALID, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage0_subdone_grp6_done_reg, ap_block_pp0_stage0_subdone_grp9_done_reg, ap_block_state4_io_grp2)
    begin
                ap_block_pp0_stage0_11001 <= (((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)) or ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg)) or ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_state4_io_grp2)
    begin
                ap_block_pp0_stage0_11001_grp2 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp6_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter6, m_axi_g0_0_AWREADY, m_axi_g0_0_RVALID, ap_block_pp0_stage0_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp6 <= (((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)) or ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)));
    end process;


    ap_block_pp0_stage0_11001_grp9_assign_proc : process(ap_enable_reg_pp0_iter8, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp9_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp9 <= ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp9 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter8, m_axi_g0_0_AWREADY, m_axi_g0_0_RVALID, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage0_subdone_grp6_done_reg, ap_block_pp0_stage0_subdone_grp9_done_reg, ap_block_state4_io_grp2)
    begin
                ap_block_pp0_stage0_subdone <= (((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)) or ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg)) or ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_state4_io_grp2)
    begin
                ap_block_pp0_stage0_subdone_grp2 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp6_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter6, m_axi_g0_0_AWREADY, m_axi_g0_0_RVALID, ap_block_pp0_stage0_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp6 <= (((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)) or ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)));
    end process;


    ap_block_pp0_stage0_subdone_grp9_assign_proc : process(ap_enable_reg_pp0_iter8, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp9_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp9 <= ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_01001_grp8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter6, m_axi_g0_0_WREADY, m_axi_g0_0_ARREADY, m_axi_g0_0_RVALID, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage1_subdone_grp3_done_reg, ap_block_pp0_stage1_subdone_grp8_done_reg)
    begin
                ap_block_pp0_stage1_11001 <= (((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp8_done_reg)) or ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg)) or ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg)));
    end process;

        ap_block_pp0_stage1_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_g0_0_ARREADY, ap_block_pp0_stage1_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp3 <= ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg));
    end process;


    ap_block_pp0_stage1_11001_grp4_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_g0_0_RVALID, ap_block_pp0_stage1_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp4 <= ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg));
    end process;


    ap_block_pp0_stage1_11001_grp8_assign_proc : process(ap_enable_reg_pp0_iter6, m_axi_g0_0_WREADY, ap_block_pp0_stage1_subdone_grp8_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp8 <= ((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp8_done_reg));
    end process;

        ap_block_pp0_stage1_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter6, m_axi_g0_0_WREADY, m_axi_g0_0_ARREADY, m_axi_g0_0_RVALID, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage1_subdone_grp3_done_reg, ap_block_pp0_stage1_subdone_grp8_done_reg)
    begin
                ap_block_pp0_stage1_subdone <= (((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp8_done_reg)) or ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg)) or ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg)));
    end process;

        ap_block_pp0_stage1_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_grp3_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_g0_0_ARREADY, ap_block_pp0_stage1_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp3 <= ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg));
    end process;


    ap_block_pp0_stage1_subdone_grp4_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_g0_0_RVALID, ap_block_pp0_stage1_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp4 <= ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg));
    end process;


    ap_block_pp0_stage1_subdone_grp8_assign_proc : process(ap_enable_reg_pp0_iter6, m_axi_g0_0_WREADY, ap_block_pp0_stage1_subdone_grp8_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp8 <= ((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp8_done_reg));
    end process;


    ap_block_pp0_stage2_11001_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_g0_0_RVALID, ap_block_state3_io_grp1, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_pp0_stage2_subdone_grp5_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage2_11001 <= (((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5_done_reg)) or ((ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg)));
    end process;

        ap_block_pp0_stage2_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_grp1_assign_proc : process(ap_block_state3_io_grp1, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage2_11001_grp1 <= ((ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg));
    end process;


    ap_block_pp0_stage2_11001_grp5_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_g0_0_RVALID, ap_block_pp0_stage2_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage2_11001_grp5 <= ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5_done_reg));
    end process;

        ap_block_pp0_stage2_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_grp5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_g0_0_RVALID, ap_block_state3_io_grp1, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_pp0_stage2_subdone_grp5_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage2_subdone <= (((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5_done_reg)) or ((ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg)));
    end process;

        ap_block_pp0_stage2_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_grp1_assign_proc : process(ap_block_state3_io_grp1, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage2_subdone_grp1 <= ((ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg));
    end process;


    ap_block_pp0_stage2_subdone_grp5_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_g0_0_RVALID, ap_block_pp0_stage2_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage2_subdone_grp5 <= ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5_done_reg));
    end process;


    ap_block_state3_io_grp1_assign_proc : process(m_axi_g0_0_ARREADY, icmp_ln795_reg_734)
    begin
                ap_block_state3_io_grp1 <= ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (icmp_ln795_reg_734 = ap_const_lv1_0));
    end process;


    ap_block_state4_io_grp2_assign_proc : process(m_axi_g0_0_ARREADY, icmp_ln795_reg_734)
    begin
                ap_block_state4_io_grp2 <= ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (icmp_ln795_reg_734 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln795_reg_734, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (icmp_ln795_reg_734 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter7_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_subdone, icmp_ln795_reg_734_pp0_iter6_reg)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (icmp_ln795_reg_734_pp0_iter6_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter7_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter7_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter7_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to6_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to6 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to6 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    empty_73_fu_378_p2 <= (icmp_ln798_mid211_fu_358_p2 or and_ln795_1_fu_306_p2);
    empty_74_fu_384_p2 <= (icmp_ln796_fu_274_p2 or empty_73_fu_378_p2);
    empty_fu_326_p2 <= (icmp_ln796_fu_274_p2 or and_ln795_1_fu_306_p2);
    exitcond_flatten_not_fu_340_p2 <= (icmp_ln797_fu_300_p2 xor ap_const_lv1_1);

    g0_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, m_axi_g0_0_ARREADY, icmp_ln795_reg_734, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage2_grp1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_grp2, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage1_grp3, ap_block_pp0_stage1_subdone_grp3_done_reg)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (icmp_ln795_reg_734 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp2) and (icmp_ln795_reg_734 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp3)))) then 
            g0_blk_n_AR <= m_axi_g0_0_ARREADY;
        else 
            g0_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_AW_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter6, m_axi_g0_0_AWREADY, ap_block_pp0_stage0_grp6, ap_block_pp0_stage0_subdone_grp6_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp6))) then 
            g0_blk_n_AW <= m_axi_g0_0_AWREADY;
        else 
            g0_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_B_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter8, m_axi_g0_0_BVALID, ap_block_pp0_stage0_grp9, ap_block_pp0_stage0_subdone_grp9_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp9))) then 
            g0_blk_n_B <= m_axi_g0_0_BVALID;
        else 
            g0_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage2, m_axi_g0_0_RVALID, ap_block_pp0_stage2_subdone_grp5_done_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp4, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage2_grp5, ap_block_pp0_stage0_grp6, ap_block_pp0_stage0_subdone_grp6_done_reg)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp6)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5_done_reg)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp4)))) then 
            g0_blk_n_R <= m_axi_g0_0_RVALID;
        else 
            g0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter6, m_axi_g0_0_WREADY, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp8, ap_block_pp0_stage1_subdone_grp8_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp8_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp8))) then 
            g0_blk_n_W <= m_axi_g0_0_WREADY;
        else 
            g0_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_192_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_block_pp0_stage2_11001_grp0, ap_block_pp0_stage2_subdone_grp0_done_reg, ap_block_pp0_stage1_11001_grp0, ap_block_pp0_stage1_subdone_grp0_done_reg)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0)))) then 
            grp_fu_192_ce <= ap_const_logic_1;
        else 
            grp_fu_192_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_192_p0 <= g0_addr_19_read_reg_801;

    grp_fu_196_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_block_pp0_stage2_11001_grp0, ap_block_pp0_stage2_subdone_grp0_done_reg, ap_block_pp0_stage1_11001_grp0, ap_block_pp0_stage1_subdone_grp0_done_reg)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0)))) then 
            grp_fu_196_ce <= ap_const_logic_1;
        else 
            grp_fu_196_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_196_p0 <= g0_addr_read_reg_781;
    grp_fu_196_p1 <= g0_addr_18_read_reg_786;
    icmp_ln795_fu_238_p2 <= "1" when (indvar_flatten35_fu_138 = ap_const_lv21_180000) else "0";
    icmp_ln796_fu_274_p2 <= "1" when (indvar_flatten12_fu_130 = ap_const_lv16_6000) else "0";
    icmp_ln797_fu_300_p2 <= "1" when (indvar_flatten_fu_122 = ap_const_lv13_800) else "0";
    icmp_ln798_fu_294_p2 <= "1" when (v327_fu_114 = ap_const_lv6_20) else "0";
    icmp_ln798_mid211_fu_358_p2 <= (icmp_ln798_fu_294_p2 and and_ln795_fu_352_p2);

    m_axi_g0_0_ARADDR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, icmp_ln795_reg_734, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage1_subdone_grp3_done_reg, g0_addr_reg_754, g0_addr_18_reg_766, g0_addr_19_reg_772, ap_block_pp0_stage2_11001_grp1, ap_block_pp0_stage0_11001_grp2, ap_block_pp0_stage1_11001_grp3)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg))) then 
            m_axi_g0_0_ARADDR <= g0_addr_19_reg_772;
        elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (icmp_ln795_reg_734 = ap_const_lv1_0))) then 
            m_axi_g0_0_ARADDR <= g0_addr_18_reg_766;
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (icmp_ln795_reg_734 = ap_const_lv1_0))) then 
            m_axi_g0_0_ARADDR <= g0_addr_reg_754;
        else 
            m_axi_g0_0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axi_g0_0_ARBURST <= ap_const_lv2_0;
    m_axi_g0_0_ARCACHE <= ap_const_lv4_0;
    m_axi_g0_0_ARID <= ap_const_lv1_0;
    m_axi_g0_0_ARLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_g0_0_ARLOCK <= ap_const_lv2_0;
    m_axi_g0_0_ARPROT <= ap_const_lv3_0;
    m_axi_g0_0_ARQOS <= ap_const_lv4_0;
    m_axi_g0_0_ARREGION <= ap_const_lv4_0;
    m_axi_g0_0_ARSIZE <= ap_const_lv3_0;
    m_axi_g0_0_ARUSER <= ap_const_lv1_0;

    m_axi_g0_0_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, icmp_ln795_reg_734, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage1_subdone_grp3_done_reg, ap_block_pp0_stage2_11001_grp1, ap_block_pp0_stage0_11001_grp2, ap_block_pp0_stage1_11001_grp3)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (icmp_ln795_reg_734 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (icmp_ln795_reg_734 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg)))) then 
            m_axi_g0_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_g0_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_g0_0_AWADDR <= g0_addr_19_reg_772_pp0_iter5_reg;
    m_axi_g0_0_AWBURST <= ap_const_lv2_0;
    m_axi_g0_0_AWCACHE <= ap_const_lv4_0;
    m_axi_g0_0_AWID <= ap_const_lv1_0;
    m_axi_g0_0_AWLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_g0_0_AWLOCK <= ap_const_lv2_0;
    m_axi_g0_0_AWPROT <= ap_const_lv3_0;
    m_axi_g0_0_AWQOS <= ap_const_lv4_0;
    m_axi_g0_0_AWREGION <= ap_const_lv4_0;
    m_axi_g0_0_AWSIZE <= ap_const_lv3_0;
    m_axi_g0_0_AWUSER <= ap_const_lv1_0;

    m_axi_g0_0_AWVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone_grp6_done_reg, ap_block_pp0_stage0_11001_grp6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg))) then 
            m_axi_g0_0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_g0_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_g0_0_BREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_subdone_grp9_done_reg, ap_block_pp0_stage0_11001_grp9)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp9) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg))) then 
            m_axi_g0_0_BREADY <= ap_const_logic_1;
        else 
            m_axi_g0_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_g0_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone_grp5_done_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage0_subdone_grp6_done_reg, ap_block_pp0_stage0_11001_grp6, ap_block_pp0_stage2_11001_grp5, ap_block_pp0_stage1_11001_grp4)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5_done_reg)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg)))) then 
            m_axi_g0_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_g0_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_g0_0_WDATA <= v332_reg_816;
    m_axi_g0_0_WID <= ap_const_lv1_0;
    m_axi_g0_0_WLAST <= ap_const_logic_0;
    m_axi_g0_0_WSTRB <= ap_const_lv4_F;
    m_axi_g0_0_WUSER <= ap_const_lv1_0;

    m_axi_g0_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter6, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp8_done_reg, ap_block_pp0_stage1_11001_grp8)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp8) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp8_done_reg))) then 
            m_axi_g0_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_g0_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    not_exitcond_flatten_mid234_fu_346_p2 <= (icmp_ln796_fu_274_p2 or exitcond_flatten_not_fu_340_p2);
    select_ln795_1_fu_312_p3 <= 
        add_ln795_fu_268_p2 when (icmp_ln796_fu_274_p2(0) = '1') else 
        v324_fu_134;
    select_ln795_fu_280_p3 <= 
        ap_const_lv4_0 when (icmp_ln796_fu_274_p2(0) = '1') else 
        v325_fu_126;
    select_ln796_1_fu_501_p3 <= 
        ap_const_lv16_1 when (icmp_ln796_fu_274_p2(0) = '1') else 
        add_ln796_1_fu_495_p2;
    select_ln796_fu_364_p3 <= 
        add_ln796_fu_320_p2 when (and_ln795_1_fu_306_p2(0) = '1') else 
        select_ln795_fu_280_p3;
    select_ln797_1_fu_487_p3 <= 
        ap_const_lv13_1 when (empty_fu_326_p2(0) = '1') else 
        add_ln797_1_fu_481_p2;
    select_ln797_fu_398_p3 <= 
        add_ln797_fu_372_p2 when (icmp_ln798_mid211_fu_358_p2(0) = '1') else 
        v326_mid26_fu_332_p3;
        sext_ln803_fu_461_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_451_p4),64));

        sext_ln804_fu_590_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln13_fu_580_p4),64));

        sext_ln805_fu_644_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln14_fu_634_p4),64));

    shl_ln2_fu_600_p3 <= (select_ln796_reg_738 & ap_const_lv13_0);
    shl_ln804_2_fu_544_p3 <= (trunc_ln803_reg_744 & ap_const_lv7_0);
    shl_ln_fu_410_p3 <= (trunc_ln803_fu_406_p1 & ap_const_lv2_0);
    tmp1_fu_431_p4 <= ((select_ln796_fu_364_p3 & trunc_ln803_1_fu_427_p1) & ap_const_lv8_0);
    tmp3_fu_560_p5 <= (((select_ln796_reg_738 & ap_const_lv6_0) & trunc_ln804_reg_760) & ap_const_lv2_0);
    tmp5_fu_616_p4 <= ((trunc_ln803_1_reg_749 & trunc_ln804_reg_760) & ap_const_lv2_0);
    trunc_ln13_fu_580_p4 <= add_ln804_1_fu_574_p2(63 downto 2);
    trunc_ln14_fu_634_p4 <= add_ln805_1_fu_628_p2(63 downto 2);
    trunc_ln803_1_fu_427_p1 <= select_ln797_fu_398_p3(6 - 1 downto 0);
    trunc_ln803_fu_406_p1 <= select_ln795_1_fu_312_p3(6 - 1 downto 0);
    trunc_ln804_fu_471_p1 <= v327_mid2_fu_390_p3(5 - 1 downto 0);
    trunc_ln_fu_451_p4 <= add_ln803_1_fu_445_p2(63 downto 2);
    v326_mid26_fu_332_p3 <= 
        ap_const_lv7_0 when (empty_fu_326_p2(0) = '1') else 
        v326_fu_118;
    v327_mid2_fu_390_p3 <= 
        ap_const_lv6_0 when (empty_74_fu_384_p2(0) = '1') else 
        v327_fu_114;
    xor_ln795_fu_288_p2 <= (icmp_ln796_fu_274_p2 xor ap_const_lv1_1);
    zext_ln796_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln804_2_fu_544_p3),64));
    zext_ln797_fu_607_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln2_fu_600_p3),64));
    zext_ln803_fu_441_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp1_fu_431_p4),64));
    zext_ln804_1_fu_570_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp3_fu_560_p5),64));
    zext_ln804_fu_418_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_410_p3),64));
    zext_ln805_fu_624_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp5_fu_616_p4),64));
end behav;
