-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity control_control_Pipeline_VITIS_LOOP_207_1_VITIS_LOOP_208_2_VITIS_LOOP_209_342 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_g0_0_AWVALID : OUT STD_LOGIC;
    m_axi_g0_0_AWREADY : IN STD_LOGIC;
    m_axi_g0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_g0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_WVALID : OUT STD_LOGIC;
    m_axi_g0_0_WREADY : IN STD_LOGIC;
    m_axi_g0_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_WLAST : OUT STD_LOGIC;
    m_axi_g0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_ARVALID : OUT STD_LOGIC;
    m_axi_g0_0_ARREADY : IN STD_LOGIC;
    m_axi_g0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_g0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_RVALID : IN STD_LOGIC;
    m_axi_g0_0_RREADY : OUT STD_LOGIC;
    m_axi_g0_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_RLAST : IN STD_LOGIC;
    m_axi_g0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_g0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_BVALID : IN STD_LOGIC;
    m_axi_g0_0_BREADY : OUT STD_LOGIC;
    m_axi_g0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    sext_ln615_1 : IN STD_LOGIC_VECTOR (61 downto 0);
    sext_ln2159 : IN STD_LOGIC_VECTOR (61 downto 0);
    sext_ln615_4 : IN STD_LOGIC_VECTOR (61 downto 0);
    v1050 : IN STD_LOGIC_VECTOR (63 downto 0);
    grp_fu_7589_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_7589_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_7589_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
    grp_fu_7589_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
    grp_fu_7589_p_ce : OUT STD_LOGIC );
end;


architecture behav of control_control_Pipeline_VITIS_LOOP_207_1_VITIS_LOOP_208_2_VITIS_LOOP_209_342 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv17_18000 : STD_LOGIC_VECTOR (16 downto 0) := "11000000000000000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv8_40 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp4_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp4 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp5_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp5 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp7_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp7 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal icmp_ln207_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal g0_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal icmp_ln207_reg_517 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal g0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp3_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp3 : BOOLEAN;
    signal ap_block_pp0_stage1_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_grp4 : BOOLEAN;
    signal g0_blk_n_AW : STD_LOGIC;
    signal ap_block_pp0_stage1_grp5 : BOOLEAN;
    signal g0_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage0_grp6 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp6_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp6 : BOOLEAN;
    signal g0_blk_n_B : STD_LOGIC;
    signal ap_block_pp0_stage1_grp7 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp6 : BOOLEAN;
    signal sext_ln615_4_cast_fu_184_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal sext_ln615_4_cast_reg_512 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal select_ln207_2_fu_278_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln207_2_reg_521 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln209_fu_314_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln209_reg_526 : STD_LOGIC_VECTOR (2 downto 0);
    signal g0_addr_reg_531 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln214_fu_357_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln214_reg_537 : STD_LOGIC_VECTOR (2 downto 0);
    signal g0_addr_104_reg_542 : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_104_reg_542_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_104_reg_542_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_104_reg_542_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_104_reg_542_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_104_reg_542_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_104_reg_542_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_read_reg_551 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001_grp3 : BOOLEAN;
    signal g0_addr_104_read_reg_556 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_11001_grp4 : BOOLEAN;
    signal v79_fu_460_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal v80_fu_464_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal v81_reg_571 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp0 : BOOLEAN;
    signal sext_ln213_fu_347_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal sext_ln214_fu_450_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state3_io_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp5 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp6 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp7 : BOOLEAN;
    signal v78_fu_104 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln209_fu_361_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal v77_fu_108 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal select_ln208_fu_306_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten14694_fu_112 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln208_2_fu_373_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal v76_fu_116 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal indvar_flatten14707_fu_120 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal add_ln207_fu_222_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal icmp_ln208_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln209_fu_266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln207_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln207_2_fu_240_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln207_fu_252_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln207_fu_272_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln208_fu_286_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal v78_2_mid2_fu_298_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_322_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln209_fu_318_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln213_fu_336_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal zext_ln213_fu_332_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln213_2_fu_341_p2 : STD_LOGIC_VECTOR (62 downto 0);
    signal add_ln208_2_fu_367_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln214_4_fu_406_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln208_fu_413_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp19_fu_422_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln214_fu_430_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln214_fu_417_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln214_2_fu_434_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln214_2_fu_440_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_block_pp0_stage0_00001_grp0 : BOOLEAN;
    signal grp_fu_180_ce : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_662 : BOOLEAN;
    signal ap_condition_666 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component control_faddfsub_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component control_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component control_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                        ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp3_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3)) then 
                        ap_block_pp0_stage0_subdone_grp3_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp6_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp6_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp6_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6)) then 
                        ap_block_pp0_stage0_subdone_grp6_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2)) then 
                        ap_block_pp0_stage1_subdone_grp2_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp4_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4)) then 
                        ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp5_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp5_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp5_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp5)) then 
                        ap_block_pp0_stage1_subdone_grp5_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp7_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp7_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp7_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp7)) then 
                        ap_block_pp0_stage1_subdone_grp7_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten14694_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                indvar_flatten14694_fu_112 <= ap_const_lv8_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln207_fu_216_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                indvar_flatten14694_fu_112 <= select_ln208_2_fu_373_p3;
            end if; 
        end if;
    end process;

    indvar_flatten14707_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                indvar_flatten14707_fu_120 <= ap_const_lv17_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln207_fu_216_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                indvar_flatten14707_fu_120 <= add_ln207_fu_222_p2;
            end if; 
        end if;
    end process;

    v76_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                v76_fu_116 <= ap_const_lv11_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln207_fu_216_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                v76_fu_116 <= select_ln207_2_fu_278_p3;
            end if; 
        end if;
    end process;

    v77_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                v77_fu_108 <= ap_const_lv4_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln207_fu_216_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                v77_fu_108 <= select_ln208_fu_306_p3;
            end if; 
        end if;
    end process;

    v78_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                v78_fu_104 <= ap_const_lv4_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln207_fu_216_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                v78_fu_104 <= add_ln209_fu_361_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                g0_addr_reg_531 <= sext_ln213_fu_347_p1;
                icmp_ln207_reg_517 <= icmp_ln207_fu_216_p2;
                select_ln207_2_reg_521 <= select_ln207_2_fu_278_p3;
                trunc_ln209_reg_526 <= trunc_ln209_fu_314_p1;
                trunc_ln214_reg_537 <= trunc_ln214_fu_357_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg))) then
                g0_addr_104_read_reg_556 <= m_axi_g0_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg))) then
                g0_addr_104_reg_542 <= sext_ln214_fu_450_p1;
                g0_addr_104_reg_542_pp0_iter2_reg <= g0_addr_104_reg_542;
                g0_addr_104_reg_542_pp0_iter3_reg <= g0_addr_104_reg_542_pp0_iter2_reg;
                g0_addr_104_reg_542_pp0_iter4_reg <= g0_addr_104_reg_542_pp0_iter3_reg;
                g0_addr_104_reg_542_pp0_iter5_reg <= g0_addr_104_reg_542_pp0_iter4_reg;
                g0_addr_104_reg_542_pp0_iter6_reg <= g0_addr_104_reg_542_pp0_iter5_reg;
                g0_addr_104_reg_542_pp0_iter7_reg <= g0_addr_104_reg_542_pp0_iter6_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg))) then
                g0_addr_read_reg_551 <= m_axi_g0_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                sext_ln615_4_cast_reg_512 <= sext_ln615_4_cast_fu_184_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0))) then
                v81_reg_571 <= grp_fu_7589_p_dout0;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    add_ln207_2_fu_240_p2 <= std_logic_vector(unsigned(v76_fu_116) + unsigned(ap_const_lv11_1));
    add_ln207_fu_222_p2 <= std_logic_vector(unsigned(indvar_flatten14707_fu_120) + unsigned(ap_const_lv17_1));
    add_ln208_2_fu_367_p2 <= std_logic_vector(unsigned(indvar_flatten14694_fu_112) + unsigned(ap_const_lv8_1));
    add_ln208_fu_286_p2 <= std_logic_vector(unsigned(select_ln207_fu_252_p3) + unsigned(ap_const_lv4_1));
    add_ln209_fu_361_p2 <= std_logic_vector(unsigned(v78_2_mid2_fu_298_p3) + unsigned(ap_const_lv4_1));
    add_ln213_2_fu_341_p2 <= std_logic_vector(unsigned(add_ln213_fu_336_p2) + unsigned(zext_ln213_fu_332_p1));
    add_ln213_fu_336_p2 <= std_logic_vector(unsigned(zext_ln209_fu_318_p1) + unsigned(sext_ln615_4_cast_reg_512));
    add_ln214_2_fu_434_p2 <= std_logic_vector(unsigned(zext_ln214_fu_430_p1) + unsigned(add_ln214_fu_417_p2));
    add_ln214_fu_417_p2 <= std_logic_vector(unsigned(zext_ln208_fu_413_p1) + unsigned(v1050));
    and_ln207_fu_272_p2 <= (xor_ln207_fu_260_p2 and icmp_ln209_fu_266_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
        ap_block_pp0_stage0_00001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001_grp6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter8, m_axi_g0_0_WREADY, m_axi_g0_0_RVALID, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_subdone_grp6_done_reg, ap_block_state3_io_grp1)
    begin
                ap_block_pp0_stage0_11001 <= (((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (m_axi_g0_0_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state3_io_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter5, m_axi_g0_0_RVALID, ap_block_pp0_stage0_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp3 <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (m_axi_g0_0_RVALID = ap_const_logic_0));
    end process;


    ap_block_pp0_stage0_11001_grp6_assign_proc : process(ap_enable_reg_pp0_iter8, m_axi_g0_0_WREADY, ap_block_pp0_stage0_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp6 <= ((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter8, m_axi_g0_0_WREADY, m_axi_g0_0_RVALID, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_subdone_grp6_done_reg, ap_block_state3_io_grp1)
    begin
                ap_block_pp0_stage0_subdone <= (((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (m_axi_g0_0_RVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state3_io_grp1)
    begin
                ap_block_pp0_stage0_subdone_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp3_assign_proc : process(ap_enable_reg_pp0_iter5, m_axi_g0_0_RVALID, ap_block_pp0_stage0_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp3 <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (m_axi_g0_0_RVALID = ap_const_logic_0));
    end process;


    ap_block_pp0_stage0_subdone_grp6_assign_proc : process(ap_enable_reg_pp0_iter8, m_axi_g0_0_WREADY, ap_block_pp0_stage0_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp6 <= ((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter10, m_axi_g0_0_AWREADY, m_axi_g0_0_ARREADY, m_axi_g0_0_RVALID, m_axi_g0_0_BVALID, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage1_subdone_grp5_done_reg, ap_block_pp0_stage1_subdone_grp7_done_reg)
    begin
                ap_block_pp0_stage1_11001 <= (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp7_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0)) or ((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp5_done_reg)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg) and (m_axi_g0_0_RVALID = ap_const_logic_0)) or ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg)));
    end process;

        ap_block_pp0_stage1_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_g0_0_ARREADY, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp2 <= ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage1_11001_grp4_assign_proc : process(ap_enable_reg_pp0_iter5, m_axi_g0_0_RVALID, ap_block_pp0_stage1_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp4 <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg) and (m_axi_g0_0_RVALID = ap_const_logic_0));
    end process;


    ap_block_pp0_stage1_11001_grp5_assign_proc : process(ap_enable_reg_pp0_iter7, m_axi_g0_0_AWREADY, ap_block_pp0_stage1_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp5 <= ((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp5_done_reg));
    end process;


    ap_block_pp0_stage1_11001_grp7_assign_proc : process(ap_enable_reg_pp0_iter10, m_axi_g0_0_BVALID, ap_block_pp0_stage1_subdone_grp7_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp7 <= ((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp7_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0));
    end process;

        ap_block_pp0_stage1_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter10, m_axi_g0_0_AWREADY, m_axi_g0_0_ARREADY, m_axi_g0_0_RVALID, m_axi_g0_0_BVALID, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage1_subdone_grp5_done_reg, ap_block_pp0_stage1_subdone_grp7_done_reg)
    begin
                ap_block_pp0_stage1_subdone <= (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp7_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0)) or ((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp5_done_reg)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg) and (m_axi_g0_0_RVALID = ap_const_logic_0)) or ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg)));
    end process;

        ap_block_pp0_stage1_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_g0_0_ARREADY, ap_block_pp0_stage1_subdone_grp2_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp2 <= ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage1_subdone_grp4_assign_proc : process(ap_enable_reg_pp0_iter5, m_axi_g0_0_RVALID, ap_block_pp0_stage1_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp4 <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg) and (m_axi_g0_0_RVALID = ap_const_logic_0));
    end process;


    ap_block_pp0_stage1_subdone_grp5_assign_proc : process(ap_enable_reg_pp0_iter7, m_axi_g0_0_AWREADY, ap_block_pp0_stage1_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp5 <= ((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp5_done_reg));
    end process;


    ap_block_pp0_stage1_subdone_grp7_assign_proc : process(ap_enable_reg_pp0_iter10, m_axi_g0_0_BVALID, ap_block_pp0_stage1_subdone_grp7_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp7 <= ((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp7_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0));
    end process;


    ap_block_state3_io_grp1_assign_proc : process(m_axi_g0_0_ARREADY, icmp_ln207_reg_517)
    begin
                ap_block_state3_io_grp1 <= ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (icmp_ln207_reg_517 = ap_const_lv1_0));
    end process;


    ap_condition_662_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln207_reg_517, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1)
    begin
                ap_condition_662 <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln207_reg_517 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg));
    end process;


    ap_condition_666_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage1_11001_grp2)
    begin
                ap_condition_666 <= ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg, icmp_ln207_fu_216_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (icmp_ln207_fu_216_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter9_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter9_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_292_p2 <= (icmp_ln208_fu_246_p2 or and_ln207_fu_272_p2);

    g0_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, m_axi_g0_0_ARREADY, ap_block_pp0_stage1_subdone_grp2_done_reg, ap_block_pp0_stage0_grp1, icmp_ln207_reg_517, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage1_grp2)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln207_reg_517 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1)))) then 
            g0_blk_n_AR <= m_axi_g0_0_ARREADY;
        else 
            g0_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_AW_assign_proc : process(ap_enable_reg_pp0_iter7, ap_CS_fsm_pp0_stage1, m_axi_g0_0_AWREADY, ap_block_pp0_stage1_subdone_grp5_done_reg, ap_block_pp0_stage1_grp5)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp5_done_reg))) then 
            g0_blk_n_AW <= m_axi_g0_0_AWREADY;
        else 
            g0_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_B_assign_proc : process(ap_enable_reg_pp0_iter10, ap_CS_fsm_pp0_stage1, m_axi_g0_0_BVALID, ap_block_pp0_stage1_subdone_grp7_done_reg, ap_block_pp0_stage1_grp7)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp7) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp7_done_reg))) then 
            g0_blk_n_B <= m_axi_g0_0_BVALID;
        else 
            g0_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage1, m_axi_g0_0_RVALID, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage0_grp3, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage1_grp4)
    begin
        if ((((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp3)))) then 
            g0_blk_n_R <= m_axi_g0_0_RVALID;
        else 
            g0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_W_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter8, m_axi_g0_0_WREADY, ap_block_pp0_stage0_grp6, ap_block_pp0_stage0_subdone_grp6_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp6))) then 
            g0_blk_n_W <= m_axi_g0_0_WREADY;
        else 
            g0_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_180_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_block_pp0_stage1_11001_grp0, ap_block_pp0_stage1_subdone_grp0_done_reg)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0)))) then 
            grp_fu_180_ce <= ap_const_logic_1;
        else 
            grp_fu_180_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_7589_p_ce <= grp_fu_180_ce;
    grp_fu_7589_p_din0 <= v79_fu_460_p1;
    grp_fu_7589_p_din1 <= v80_fu_464_p1;
    grp_fu_7589_p_opcode <= ap_const_lv2_0(1 - 1 downto 0);
    icmp_ln207_fu_216_p2 <= "1" when (indvar_flatten14707_fu_120 = ap_const_lv17_18000) else "0";
    icmp_ln208_fu_246_p2 <= "1" when (indvar_flatten14694_fu_112 = ap_const_lv8_40) else "0";
    icmp_ln209_fu_266_p2 <= "1" when (v78_fu_104 = ap_const_lv4_8) else "0";

    m_axi_g0_0_ARADDR_assign_proc : process(ap_enable_reg_pp0_iter1, g0_addr_reg_531, g0_addr_104_reg_542, ap_condition_662, ap_condition_666)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then
            if ((ap_const_boolean_1 = ap_condition_666)) then 
                m_axi_g0_0_ARADDR <= g0_addr_104_reg_542;
            elsif ((ap_const_boolean_1 = ap_condition_662)) then 
                m_axi_g0_0_ARADDR <= g0_addr_reg_531;
            else 
                m_axi_g0_0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            m_axi_g0_0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axi_g0_0_ARBURST <= ap_const_lv2_0;
    m_axi_g0_0_ARCACHE <= ap_const_lv4_0;
    m_axi_g0_0_ARID <= ap_const_lv1_0;
    m_axi_g0_0_ARLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_g0_0_ARLOCK <= ap_const_lv2_0;
    m_axi_g0_0_ARPROT <= ap_const_lv3_0;
    m_axi_g0_0_ARQOS <= ap_const_lv4_0;
    m_axi_g0_0_ARREGION <= ap_const_lv4_0;
    m_axi_g0_0_ARSIZE <= ap_const_lv3_0;
    m_axi_g0_0_ARUSER <= ap_const_lv1_0;

    m_axi_g0_0_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp2_done_reg, icmp_ln207_reg_517, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1, ap_block_pp0_stage1_11001_grp2)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp2_done_reg)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln207_reg_517 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg)))) then 
            m_axi_g0_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_g0_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_g0_0_AWADDR <= g0_addr_104_reg_542_pp0_iter7_reg;
    m_axi_g0_0_AWBURST <= ap_const_lv2_0;
    m_axi_g0_0_AWCACHE <= ap_const_lv4_0;
    m_axi_g0_0_AWID <= ap_const_lv1_0;
    m_axi_g0_0_AWLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_g0_0_AWLOCK <= ap_const_lv2_0;
    m_axi_g0_0_AWPROT <= ap_const_lv3_0;
    m_axi_g0_0_AWQOS <= ap_const_lv4_0;
    m_axi_g0_0_AWREGION <= ap_const_lv4_0;
    m_axi_g0_0_AWSIZE <= ap_const_lv3_0;
    m_axi_g0_0_AWUSER <= ap_const_lv1_0;

    m_axi_g0_0_AWVALID_assign_proc : process(ap_enable_reg_pp0_iter7, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp5_done_reg, ap_block_pp0_stage1_11001_grp5)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp5_done_reg))) then 
            m_axi_g0_0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_g0_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_g0_0_BREADY_assign_proc : process(ap_enable_reg_pp0_iter10, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp7_done_reg, ap_block_pp0_stage1_11001_grp7)
    begin
        if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp7) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp7_done_reg))) then 
            m_axi_g0_0_BREADY <= ap_const_logic_1;
        else 
            m_axi_g0_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_g0_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter5, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage0_subdone_grp3_done_reg, ap_block_pp0_stage0_11001_grp3, ap_block_pp0_stage1_11001_grp4)
    begin
        if ((((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp3_done_reg)))) then 
            m_axi_g0_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_g0_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_g0_0_WDATA <= v81_reg_571;
    m_axi_g0_0_WID <= ap_const_lv1_0;
    m_axi_g0_0_WLAST <= ap_const_logic_0;
    m_axi_g0_0_WSTRB <= ap_const_lv4_F;
    m_axi_g0_0_WUSER <= ap_const_lv1_0;

    m_axi_g0_0_WVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_subdone_grp6_done_reg, ap_block_pp0_stage0_11001_grp6)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg))) then 
            m_axi_g0_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_g0_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    select_ln207_2_fu_278_p3 <= 
        add_ln207_2_fu_240_p2 when (icmp_ln208_fu_246_p2(0) = '1') else 
        v76_fu_116;
    select_ln207_fu_252_p3 <= 
        ap_const_lv4_0 when (icmp_ln208_fu_246_p2(0) = '1') else 
        v77_fu_108;
    select_ln208_2_fu_373_p3 <= 
        ap_const_lv8_1 when (icmp_ln208_fu_246_p2(0) = '1') else 
        add_ln208_2_fu_367_p2;
    select_ln208_fu_306_p3 <= 
        add_ln208_fu_286_p2 when (and_ln207_fu_272_p2(0) = '1') else 
        select_ln207_fu_252_p3;
        sext_ln213_fu_347_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln213_2_fu_341_p2),64));

        sext_ln214_fu_450_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln214_2_fu_440_p4),64));

        sext_ln615_4_cast_fu_184_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln615_4),63));

    shl_ln214_4_fu_406_p3 <= (select_ln207_2_reg_521 & ap_const_lv8_0);
    tmp19_fu_422_p4 <= ((trunc_ln209_reg_526 & trunc_ln214_reg_537) & ap_const_lv2_0);
    tmp_fu_322_p4 <= ((select_ln207_2_fu_278_p3 & trunc_ln209_fu_314_p1) & ap_const_lv3_0);
    trunc_ln209_fu_314_p1 <= select_ln208_fu_306_p3(3 - 1 downto 0);
    trunc_ln214_2_fu_440_p4 <= add_ln214_2_fu_434_p2(63 downto 2);
    trunc_ln214_fu_357_p1 <= v78_2_mid2_fu_298_p3(3 - 1 downto 0);
    v78_2_mid2_fu_298_p3 <= 
        ap_const_lv4_0 when (empty_fu_292_p2(0) = '1') else 
        v78_fu_104;
    v79_fu_460_p1 <= g0_addr_read_reg_551;
    v80_fu_464_p1 <= g0_addr_104_read_reg_556;
    xor_ln207_fu_260_p2 <= (icmp_ln208_fu_246_p2 xor ap_const_lv1_1);
    zext_ln208_fu_413_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln214_4_fu_406_p3),64));
    zext_ln209_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(v78_2_mid2_fu_298_p3),63));
    zext_ln213_fu_332_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_322_p4),63));
    zext_ln214_fu_430_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp19_fu_422_p4),64));
end behav;
