-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity control_kernel63 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_g0_0_AWVALID : OUT STD_LOGIC;
    m_axi_g0_0_AWREADY : IN STD_LOGIC;
    m_axi_g0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_g0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_WVALID : OUT STD_LOGIC;
    m_axi_g0_0_WREADY : IN STD_LOGIC;
    m_axi_g0_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_WLAST : OUT STD_LOGIC;
    m_axi_g0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_ARVALID : OUT STD_LOGIC;
    m_axi_g0_0_ARREADY : IN STD_LOGIC;
    m_axi_g0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_g0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_g0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_g0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_RVALID : IN STD_LOGIC;
    m_axi_g0_0_RREADY : OUT STD_LOGIC;
    m_axi_g0_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_g0_0_RLAST : IN STD_LOGIC;
    m_axi_g0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_g0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_BVALID : IN STD_LOGIC;
    m_axi_g0_0_BREADY : OUT STD_LOGIC;
    m_axi_g0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_g0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_g0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    v345 : IN STD_LOGIC_VECTOR (63 downto 0);
    v346 : IN STD_LOGIC_VECTOR (63 downto 0);
    v347 : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of control_kernel63 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv21_180000 : STD_LOGIC_VECTOR (20 downto 0) := "110000000000000000000";
    constant ap_const_lv21_1 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv17_C000 : STD_LOGIC_VECTOR (16 downto 0) := "01100000000000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv14_1000 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal icmp_ln856_reg_736 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_io_grp1 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp5_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp5 : BOOLEAN;
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_condition_exit_pp0_iter0_stage2 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal g0_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage2_grp1 : BOOLEAN;
    signal g0_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_block_pp0_stage1_grp4 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp4_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp4 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage2_grp5 : BOOLEAN;
    signal ap_block_pp0_stage1_grp3 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp3_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp3 : BOOLEAN;
    signal ap_block_pp0_stage0_grp6 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp6_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp6 : BOOLEAN;
    signal g0_blk_n_AW : STD_LOGIC;
    signal g0_blk_n_W : STD_LOGIC;
    signal ap_block_pp0_stage1_grp8 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp8_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp8 : BOOLEAN;
    signal g0_blk_n_B : STD_LOGIC;
    signal ap_block_pp0_stage0_grp9 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp9_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp9 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp6 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal icmp_ln856_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal icmp_ln856_reg_736_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln856_reg_736_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln856_reg_736_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln856_reg_736_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln856_reg_736_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln856_reg_736_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln857_fu_366_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln857_reg_740 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln864_fu_408_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln864_reg_746 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln864_1_fu_429_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln864_1_reg_751 : STD_LOGIC_VECTOR (5 downto 0);
    signal g0_addr_reg_756 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln865_fu_473_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln865_reg_762 : STD_LOGIC_VECTOR (5 downto 0);
    signal g0_addr_14_reg_768 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2_11001_grp5 : BOOLEAN;
    signal g0_addr_15_reg_774 : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_15_reg_774_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_15_reg_774_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_15_reg_774_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_15_reg_774_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal g0_addr_read_reg_783 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage1_11001_grp4 : BOOLEAN;
    signal g0_addr_14_read_reg_788 : STD_LOGIC_VECTOR (31 downto 0);
    signal g0_addr_15_read_reg_803 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_198_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal v356_reg_808 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage2_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage2_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage2_subdone_grp0 : BOOLEAN;
    signal grp_fu_194_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal v357_reg_818 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state4_io_grp2 : BOOLEAN;
    signal sext_ln864_fu_463_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal sext_ln865_fu_592_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln866_fu_646_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage2_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp2 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp3 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp8 : BOOLEAN;
    signal ap_block_pp0_stage1_01001_grp8 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp9 : BOOLEAN;
    signal v352_fu_116 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln859_fu_477_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal v351_fu_120 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal select_ln858_fu_400_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten_fu_124 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    signal select_ln858_1_fu_489_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal v350_fu_128 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal indvar_flatten12_fu_132 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal select_ln857_1_fu_503_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal v349_fu_136 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln856_1_fu_314_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal indvar_flatten35_fu_140 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    signal add_ln856_1_fu_246_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal grp_fu_194_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal grp_fu_198_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_198_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln857_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln858_fu_302_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln856_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln856_fu_270_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal select_ln856_fu_282_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln856_1_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten_not_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten_mid234_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln856_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln859_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln857_fu_322_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal v351_mid26_fu_334_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln859_mid211_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_69_fu_380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_70_fu_386_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln858_fu_374_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln_fu_412_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln865_fu_420_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp1_fu_433_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln864_fu_443_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln864_fu_424_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln864_1_fu_447_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln_fu_453_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal v352_mid2_fu_392_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln858_1_fu_483_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln857_1_fu_497_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal shl_ln865_1_fu_546_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln857_fu_553_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp3_fu_562_p5 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln865_1_fu_572_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln865_fu_557_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln865_1_fu_576_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln11_fu_582_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal shl_ln1_fu_602_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln858_fu_609_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp5_fu_618_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln866_fu_626_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln866_fu_613_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln866_1_fu_630_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln12_fu_636_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal grp_fu_194_ce : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_block_pp0_stage1_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage1_subdone_grp0 : BOOLEAN;
    signal grp_fu_198_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_condition_exit_pp0_iter7_stage0 : STD_LOGIC;
    signal ap_idle_pp0_0to6 : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component control_fadd_32ns_32ns_32_4_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component control_fmul_32ns_32ns_32_3_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component control_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fadd_32ns_32ns_32_4_full_dsp_1_U494 : component control_fadd_32ns_32ns_32_4_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_194_p0,
        din1 => v356_reg_808,
        ce => grp_fu_194_ce,
        dout => grp_fu_194_p2);

    fmul_32ns_32ns_32_3_max_dsp_1_U495 : component control_fmul_32ns_32ns_32_3_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 3,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_198_p0,
        din1 => grp_fu_198_p1,
        ce => grp_fu_198_ce,
        dout => grp_fu_198_p2);

    flow_control_loop_pipe_sequential_init_U : component control_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage2,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                        ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2)) then 
                        ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp6_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp6_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp6_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6)) then 
                        ap_block_pp0_stage0_subdone_grp6_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp9_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp9_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                        ap_block_pp0_stage0_subdone_grp9_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9)) then 
                        ap_block_pp0_stage0_subdone_grp9_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0)) then 
                        ap_block_pp0_stage1_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp3_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp3_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp3_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3)) then 
                        ap_block_pp0_stage1_subdone_grp3_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp4_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4)) then 
                        ap_block_pp0_stage1_subdone_grp4_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage1_subdone_grp8_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage1_subdone_grp8_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then 
                        ap_block_pp0_stage1_subdone_grp8_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp8)) then 
                        ap_block_pp0_stage1_subdone_grp8_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0)) then 
                        ap_block_pp0_stage2_subdone_grp0_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage2_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp1_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1)) then 
                        ap_block_pp0_stage2_subdone_grp1_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage2_subdone_grp5_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage2_subdone_grp5_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage2)) then
                    if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then 
                        ap_block_pp0_stage2_subdone_grp5_done_reg <= ap_const_boolean_0;
                    elsif ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5)) then 
                        ap_block_pp0_stage2_subdone_grp5_done_reg <= ap_const_boolean_1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage2)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter1_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage0))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter3_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage0))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter4_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage0))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter5_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage0))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter6_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage0))) then 
                ap_loop_exit_ready_pp0_iter6_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
            end if; 
        end if;
    end process;

    ap_loop_exit_ready_pp0_iter7_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage0))) then 
                ap_loop_exit_ready_pp0_iter7_reg <= ap_const_logic_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001))) then 
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
            end if; 
        end if;
    end process;

    indvar_flatten12_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                indvar_flatten12_fu_132 <= ap_const_lv17_0;
            elsif (((icmp_ln856_fu_240_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                indvar_flatten12_fu_132 <= select_ln857_1_fu_503_p3;
            end if; 
        end if;
    end process;

    indvar_flatten35_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                indvar_flatten35_fu_140 <= ap_const_lv21_0;
            elsif (((icmp_ln856_fu_240_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                indvar_flatten35_fu_140 <= add_ln856_1_fu_246_p2;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                indvar_flatten_fu_124 <= ap_const_lv14_0;
            elsif (((icmp_ln856_fu_240_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                indvar_flatten_fu_124 <= select_ln858_1_fu_489_p3;
            end if; 
        end if;
    end process;

    v349_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                v349_fu_136 <= ap_const_lv6_0;
            elsif (((icmp_ln856_fu_240_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                v349_fu_136 <= select_ln856_1_fu_314_p3;
            end if; 
        end if;
    end process;

    v350_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                v350_fu_128 <= ap_const_lv4_0;
            elsif (((icmp_ln856_fu_240_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                v350_fu_128 <= select_ln857_fu_366_p3;
            end if; 
        end if;
    end process;

    v351_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                v351_fu_120 <= ap_const_lv7_0;
            elsif (((icmp_ln856_fu_240_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                v351_fu_120 <= select_ln858_fu_400_p3;
            end if; 
        end if;
    end process;

    v352_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then 
                v352_fu_116 <= ap_const_lv7_0;
            elsif (((icmp_ln856_fu_240_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then 
                v352_fu_116 <= add_ln859_fu_477_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5_done_reg))) then
                g0_addr_14_read_reg_788 <= m_axi_g0_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5_done_reg))) then
                g0_addr_14_reg_768 <= sext_ln865_fu_592_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg))) then
                g0_addr_15_read_reg_803 <= m_axi_g0_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg))) then
                g0_addr_15_reg_774 <= sext_ln866_fu_646_p1;
                g0_addr_15_reg_774_pp0_iter2_reg <= g0_addr_15_reg_774;
                g0_addr_15_reg_774_pp0_iter3_reg <= g0_addr_15_reg_774_pp0_iter2_reg;
                g0_addr_15_reg_774_pp0_iter4_reg <= g0_addr_15_reg_774_pp0_iter3_reg;
                g0_addr_15_reg_774_pp0_iter5_reg <= g0_addr_15_reg_774_pp0_iter4_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg))) then
                g0_addr_read_reg_783 <= m_axi_g0_0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001))) then
                g0_addr_reg_756 <= sext_ln864_fu_463_p1;
                icmp_ln856_reg_736 <= icmp_ln856_fu_240_p2;
                icmp_ln856_reg_736_pp0_iter1_reg <= icmp_ln856_reg_736;
                icmp_ln856_reg_736_pp0_iter2_reg <= icmp_ln856_reg_736_pp0_iter1_reg;
                icmp_ln856_reg_736_pp0_iter3_reg <= icmp_ln856_reg_736_pp0_iter2_reg;
                icmp_ln856_reg_736_pp0_iter4_reg <= icmp_ln856_reg_736_pp0_iter3_reg;
                icmp_ln856_reg_736_pp0_iter5_reg <= icmp_ln856_reg_736_pp0_iter4_reg;
                icmp_ln856_reg_736_pp0_iter6_reg <= icmp_ln856_reg_736_pp0_iter5_reg;
                select_ln857_reg_740 <= select_ln857_fu_366_p3;
                trunc_ln864_1_reg_751 <= trunc_ln864_1_fu_429_p1;
                trunc_ln864_reg_746 <= trunc_ln864_fu_408_p1;
                trunc_ln865_reg_762 <= trunc_ln865_fu_473_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0))) then
                v356_reg_808 <= grp_fu_198_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0))) then
                v357_reg_818 <= grp_fu_194_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_idle_pp0, ap_block_pp0_stage2_subdone, ap_block_pp0_stage1_subdone, ap_block_pp0_stage0_subdone, ap_condition_exit_pp0_iter7_stage0, ap_idle_pp0_0to6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if (((ap_idle_pp0_0to6 = ap_const_logic_1) and (ap_const_logic_1 = ap_condition_exit_pp0_iter7_stage0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_idle_pp0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln856_1_fu_246_p2 <= std_logic_vector(unsigned(indvar_flatten35_fu_140) + unsigned(ap_const_lv21_1));
    add_ln856_fu_270_p2 <= std_logic_vector(unsigned(v349_fu_136) + unsigned(ap_const_lv6_1));
    add_ln857_1_fu_497_p2 <= std_logic_vector(unsigned(indvar_flatten12_fu_132) + unsigned(ap_const_lv17_1));
    add_ln857_fu_322_p2 <= std_logic_vector(unsigned(select_ln856_fu_282_p3) + unsigned(ap_const_lv4_1));
    add_ln858_1_fu_483_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_124) + unsigned(ap_const_lv14_1));
    add_ln858_fu_374_p2 <= std_logic_vector(unsigned(v351_mid26_fu_334_p3) + unsigned(ap_const_lv7_1));
    add_ln859_fu_477_p2 <= std_logic_vector(unsigned(v352_mid2_fu_392_p3) + unsigned(ap_const_lv7_1));
    add_ln864_1_fu_447_p2 <= std_logic_vector(unsigned(zext_ln864_fu_443_p1) + unsigned(add_ln864_fu_424_p2));
    add_ln864_fu_424_p2 <= std_logic_vector(unsigned(zext_ln865_fu_420_p1) + unsigned(v345));
    add_ln865_1_fu_576_p2 <= std_logic_vector(unsigned(zext_ln865_1_fu_572_p1) + unsigned(add_ln865_fu_557_p2));
    add_ln865_fu_557_p2 <= std_logic_vector(unsigned(zext_ln857_fu_553_p1) + unsigned(v346));
    add_ln866_1_fu_630_p2 <= std_logic_vector(unsigned(zext_ln866_fu_626_p1) + unsigned(add_ln866_fu_613_p2));
    add_ln866_fu_613_p2 <= std_logic_vector(unsigned(zext_ln858_fu_609_p1) + unsigned(v347));
    and_ln856_1_fu_308_p2 <= (xor_ln856_fu_290_p2 and icmp_ln858_fu_302_p2);
    and_ln856_fu_354_p2 <= (xor_ln856_fu_290_p2 and not_exitcond_flatten_mid234_fu_348_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter8, m_axi_g0_0_AWREADY, m_axi_g0_0_RVALID, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage0_subdone_grp6_done_reg, ap_block_pp0_stage0_subdone_grp9_done_reg, ap_block_state4_io_grp2)
    begin
                ap_block_pp0_stage0_11001 <= (((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)) or ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg)) or ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_state4_io_grp2)
    begin
                ap_block_pp0_stage0_11001_grp2 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage0_11001_grp6_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter6, m_axi_g0_0_AWREADY, m_axi_g0_0_RVALID, ap_block_pp0_stage0_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp6 <= (((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)) or ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)));
    end process;


    ap_block_pp0_stage0_11001_grp9_assign_proc : process(ap_enable_reg_pp0_iter8, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp9_done_reg)
    begin
                ap_block_pp0_stage0_11001_grp9 <= ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0));
    end process;

        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp9 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter8, m_axi_g0_0_AWREADY, m_axi_g0_0_RVALID, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage0_subdone_grp6_done_reg, ap_block_pp0_stage0_subdone_grp9_done_reg, ap_block_state4_io_grp2)
    begin
                ap_block_pp0_stage0_subdone <= (((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)) or ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg)) or ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_grp2_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_state4_io_grp2)
    begin
                ap_block_pp0_stage0_subdone_grp2 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg));
    end process;


    ap_block_pp0_stage0_subdone_grp6_assign_proc : process(ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter6, m_axi_g0_0_AWREADY, m_axi_g0_0_RVALID, ap_block_pp0_stage0_subdone_grp6_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp6 <= (((m_axi_g0_0_AWREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)) or ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)));
    end process;


    ap_block_pp0_stage0_subdone_grp9_assign_proc : process(ap_enable_reg_pp0_iter8, m_axi_g0_0_BVALID, ap_block_pp0_stage0_subdone_grp9_done_reg)
    begin
                ap_block_pp0_stage0_subdone_grp9 <= ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg) and (m_axi_g0_0_BVALID = ap_const_logic_0));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_01001_grp8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter6, m_axi_g0_0_WREADY, m_axi_g0_0_ARREADY, m_axi_g0_0_RVALID, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage1_subdone_grp3_done_reg, ap_block_pp0_stage1_subdone_grp8_done_reg)
    begin
                ap_block_pp0_stage1_11001 <= (((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp8_done_reg)) or ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg)) or ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg)));
    end process;

        ap_block_pp0_stage1_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_grp3_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_g0_0_ARREADY, ap_block_pp0_stage1_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp3 <= ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg));
    end process;


    ap_block_pp0_stage1_11001_grp4_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_g0_0_RVALID, ap_block_pp0_stage1_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp4 <= ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg));
    end process;


    ap_block_pp0_stage1_11001_grp8_assign_proc : process(ap_enable_reg_pp0_iter6, m_axi_g0_0_WREADY, ap_block_pp0_stage1_subdone_grp8_done_reg)
    begin
                ap_block_pp0_stage1_11001_grp8 <= ((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp8_done_reg));
    end process;

        ap_block_pp0_stage1_grp3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage1_grp8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter6, m_axi_g0_0_WREADY, m_axi_g0_0_ARREADY, m_axi_g0_0_RVALID, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage1_subdone_grp3_done_reg, ap_block_pp0_stage1_subdone_grp8_done_reg)
    begin
                ap_block_pp0_stage1_subdone <= (((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp8_done_reg)) or ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg)) or ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg)));
    end process;

        ap_block_pp0_stage1_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_subdone_grp3_assign_proc : process(ap_enable_reg_pp0_iter1, m_axi_g0_0_ARREADY, ap_block_pp0_stage1_subdone_grp3_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp3 <= ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg));
    end process;


    ap_block_pp0_stage1_subdone_grp4_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_g0_0_RVALID, ap_block_pp0_stage1_subdone_grp4_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp4 <= ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg));
    end process;


    ap_block_pp0_stage1_subdone_grp8_assign_proc : process(ap_enable_reg_pp0_iter6, m_axi_g0_0_WREADY, ap_block_pp0_stage1_subdone_grp8_done_reg)
    begin
                ap_block_pp0_stage1_subdone_grp8 <= ((m_axi_g0_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp8_done_reg));
    end process;


    ap_block_pp0_stage2_11001_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_g0_0_RVALID, ap_block_state3_io_grp1, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_pp0_stage2_subdone_grp5_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage2_11001 <= (((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5_done_reg)) or ((ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg)));
    end process;

        ap_block_pp0_stage2_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_grp1_assign_proc : process(ap_block_state3_io_grp1, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage2_11001_grp1 <= ((ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg));
    end process;


    ap_block_pp0_stage2_11001_grp5_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_g0_0_RVALID, ap_block_pp0_stage2_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage2_11001_grp5 <= ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5_done_reg));
    end process;

        ap_block_pp0_stage2_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage2_grp5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_g0_0_RVALID, ap_block_state3_io_grp1, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_block_pp0_stage2_subdone_grp5_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage2_subdone <= (((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5_done_reg)) or ((ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg)));
    end process;

        ap_block_pp0_stage2_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_subdone_grp1_assign_proc : process(ap_block_state3_io_grp1, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg)
    begin
                ap_block_pp0_stage2_subdone_grp1 <= ((ap_const_boolean_1 = ap_block_state3_io_grp1) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg));
    end process;


    ap_block_pp0_stage2_subdone_grp5_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_g0_0_RVALID, ap_block_pp0_stage2_subdone_grp5_done_reg)
    begin
                ap_block_pp0_stage2_subdone_grp5 <= ((m_axi_g0_0_RVALID = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5_done_reg));
    end process;


    ap_block_state3_io_grp1_assign_proc : process(m_axi_g0_0_ARREADY, icmp_ln856_reg_736)
    begin
                ap_block_state3_io_grp1 <= ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (icmp_ln856_reg_736 = ap_const_lv1_0));
    end process;


    ap_block_state4_io_grp2_assign_proc : process(m_axi_g0_0_ARREADY, icmp_ln856_reg_736)
    begin
                ap_block_state4_io_grp2 <= ((m_axi_g0_0_ARREADY = ap_const_logic_0) and (icmp_ln856_reg_736 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage2_assign_proc : process(ap_CS_fsm_pp0_stage2, icmp_ln856_reg_736, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone) and (icmp_ln856_reg_736 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter7_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_subdone, icmp_ln856_reg_736_pp0_iter6_reg)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (icmp_ln856_reg_736_pp0_iter6_reg = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter7_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter7_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter7_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to6_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to6 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to6 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage2;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone, ap_enable_reg_pp0_iter0_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    empty_69_fu_380_p2 <= (icmp_ln859_mid211_fu_360_p2 or and_ln856_1_fu_308_p2);
    empty_70_fu_386_p2 <= (icmp_ln857_fu_276_p2 or empty_69_fu_380_p2);
    empty_fu_328_p2 <= (icmp_ln857_fu_276_p2 or and_ln856_1_fu_308_p2);
    exitcond_flatten_not_fu_342_p2 <= (icmp_ln858_fu_302_p2 xor ap_const_lv1_1);

    g0_blk_n_AR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, m_axi_g0_0_ARREADY, icmp_ln856_reg_736, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_block_pp0_stage2_grp1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_grp2, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage1_grp3, ap_block_pp0_stage1_subdone_grp3_done_reg)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (icmp_ln856_reg_736 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp2) and (icmp_ln856_reg_736 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp3)))) then 
            g0_blk_n_AR <= m_axi_g0_0_ARREADY;
        else 
            g0_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_AW_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter6, m_axi_g0_0_AWREADY, ap_block_pp0_stage0_grp6, ap_block_pp0_stage0_subdone_grp6_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp6))) then 
            g0_blk_n_AW <= m_axi_g0_0_AWREADY;
        else 
            g0_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_B_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter8, m_axi_g0_0_BVALID, ap_block_pp0_stage0_grp9, ap_block_pp0_stage0_subdone_grp9_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp9))) then 
            g0_blk_n_B <= m_axi_g0_0_BVALID;
        else 
            g0_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_R_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage2, m_axi_g0_0_RVALID, ap_block_pp0_stage2_subdone_grp5_done_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp4, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage2_grp5, ap_block_pp0_stage0_grp6, ap_block_pp0_stage0_subdone_grp6_done_reg)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp6)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5_done_reg)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp4)))) then 
            g0_blk_n_R <= m_axi_g0_0_RVALID;
        else 
            g0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    g0_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter6, m_axi_g0_0_WREADY, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_grp8, ap_block_pp0_stage1_subdone_grp8_done_reg)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp8_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_grp8))) then 
            g0_blk_n_W <= m_axi_g0_0_WREADY;
        else 
            g0_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_194_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_block_pp0_stage2_11001_grp0, ap_block_pp0_stage2_subdone_grp0_done_reg, ap_block_pp0_stage1_11001_grp0, ap_block_pp0_stage1_subdone_grp0_done_reg)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0)))) then 
            grp_fu_194_ce <= ap_const_logic_1;
        else 
            grp_fu_194_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_194_p0 <= g0_addr_15_read_reg_803;

    grp_fu_198_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg, ap_block_pp0_stage2_11001_grp0, ap_block_pp0_stage2_subdone_grp0_done_reg, ap_block_pp0_stage1_11001_grp0, ap_block_pp0_stage1_subdone_grp0_done_reg)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp0)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0)) or ((ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp0)))) then 
            grp_fu_198_ce <= ap_const_logic_1;
        else 
            grp_fu_198_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_198_p0 <= g0_addr_read_reg_783;
    grp_fu_198_p1 <= g0_addr_14_read_reg_788;
    icmp_ln856_fu_240_p2 <= "1" when (indvar_flatten35_fu_140 = ap_const_lv21_180000) else "0";
    icmp_ln857_fu_276_p2 <= "1" when (indvar_flatten12_fu_132 = ap_const_lv17_C000) else "0";
    icmp_ln858_fu_302_p2 <= "1" when (indvar_flatten_fu_124 = ap_const_lv14_1000) else "0";
    icmp_ln859_fu_296_p2 <= "1" when (v352_fu_116 = ap_const_lv7_40) else "0";
    icmp_ln859_mid211_fu_360_p2 <= (icmp_ln859_fu_296_p2 and and_ln856_fu_354_p2);

    m_axi_g0_0_ARADDR_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, icmp_ln856_reg_736, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage1_subdone_grp3_done_reg, g0_addr_reg_756, g0_addr_14_reg_768, g0_addr_15_reg_774, ap_block_pp0_stage2_11001_grp1, ap_block_pp0_stage0_11001_grp2, ap_block_pp0_stage1_11001_grp3)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg))) then 
            m_axi_g0_0_ARADDR <= g0_addr_15_reg_774;
        elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (icmp_ln856_reg_736 = ap_const_lv1_0))) then 
            m_axi_g0_0_ARADDR <= g0_addr_14_reg_768;
        elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (icmp_ln856_reg_736 = ap_const_lv1_0))) then 
            m_axi_g0_0_ARADDR <= g0_addr_reg_756;
        else 
            m_axi_g0_0_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axi_g0_0_ARBURST <= ap_const_lv2_0;
    m_axi_g0_0_ARCACHE <= ap_const_lv4_0;
    m_axi_g0_0_ARID <= ap_const_lv1_0;
    m_axi_g0_0_ARLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_g0_0_ARLOCK <= ap_const_lv2_0;
    m_axi_g0_0_ARPROT <= ap_const_lv3_0;
    m_axi_g0_0_ARQOS <= ap_const_lv4_0;
    m_axi_g0_0_ARREGION <= ap_const_lv4_0;
    m_axi_g0_0_ARSIZE <= ap_const_lv3_0;
    m_axi_g0_0_ARUSER <= ap_const_lv1_0;

    m_axi_g0_0_ARVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage2, icmp_ln856_reg_736, ap_block_pp0_stage2_subdone_grp1_done_reg, ap_enable_reg_pp0_iter0_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage1_subdone_grp3_done_reg, ap_block_pp0_stage2_11001_grp1, ap_block_pp0_stage0_11001_grp2, ap_block_pp0_stage1_11001_grp3)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_enable_reg_pp0_iter0_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp1) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp1_done_reg) and (icmp_ln856_reg_736 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (icmp_ln856_reg_736 = ap_const_lv1_0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp3) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp3_done_reg)))) then 
            m_axi_g0_0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_g0_0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_g0_0_AWADDR <= g0_addr_15_reg_774_pp0_iter5_reg;
    m_axi_g0_0_AWBURST <= ap_const_lv2_0;
    m_axi_g0_0_AWCACHE <= ap_const_lv4_0;
    m_axi_g0_0_AWID <= ap_const_lv1_0;
    m_axi_g0_0_AWLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_g0_0_AWLOCK <= ap_const_lv2_0;
    m_axi_g0_0_AWPROT <= ap_const_lv3_0;
    m_axi_g0_0_AWQOS <= ap_const_lv4_0;
    m_axi_g0_0_AWREGION <= ap_const_lv4_0;
    m_axi_g0_0_AWSIZE <= ap_const_lv3_0;
    m_axi_g0_0_AWUSER <= ap_const_lv1_0;

    m_axi_g0_0_AWVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone_grp6_done_reg, ap_block_pp0_stage0_11001_grp6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg))) then 
            m_axi_g0_0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_g0_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_g0_0_BREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter8, ap_block_pp0_stage0_subdone_grp9_done_reg, ap_block_pp0_stage0_11001_grp9)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp9) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp9_done_reg))) then 
            m_axi_g0_0_BREADY <= ap_const_logic_1;
        else 
            m_axi_g0_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_g0_0_RREADY_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2_subdone_grp5_done_reg, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp4_done_reg, ap_block_pp0_stage0_subdone_grp6_done_reg, ap_block_pp0_stage0_11001_grp6, ap_block_pp0_stage2_11001_grp5, ap_block_pp0_stage1_11001_grp4)
    begin
        if ((((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp6) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp6_done_reg)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (ap_const_boolean_0 = ap_block_pp0_stage2_11001_grp5) and (ap_const_boolean_0 = ap_block_pp0_stage2_subdone_grp5_done_reg)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp4) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp4_done_reg)))) then 
            m_axi_g0_0_RREADY <= ap_const_logic_1;
        else 
            m_axi_g0_0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_g0_0_WDATA <= v357_reg_818;
    m_axi_g0_0_WID <= ap_const_lv1_0;
    m_axi_g0_0_WLAST <= ap_const_logic_0;
    m_axi_g0_0_WSTRB <= ap_const_lv4_F;
    m_axi_g0_0_WUSER <= ap_const_lv1_0;

    m_axi_g0_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter6, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone_grp8_done_reg, ap_block_pp0_stage1_11001_grp8)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1) and (ap_const_boolean_0 = ap_block_pp0_stage1_11001_grp8) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone_grp8_done_reg))) then 
            m_axi_g0_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_g0_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    not_exitcond_flatten_mid234_fu_348_p2 <= (icmp_ln857_fu_276_p2 or exitcond_flatten_not_fu_342_p2);
    select_ln856_1_fu_314_p3 <= 
        add_ln856_fu_270_p2 when (icmp_ln857_fu_276_p2(0) = '1') else 
        v349_fu_136;
    select_ln856_fu_282_p3 <= 
        ap_const_lv4_0 when (icmp_ln857_fu_276_p2(0) = '1') else 
        v350_fu_128;
    select_ln857_1_fu_503_p3 <= 
        ap_const_lv17_1 when (icmp_ln857_fu_276_p2(0) = '1') else 
        add_ln857_1_fu_497_p2;
    select_ln857_fu_366_p3 <= 
        add_ln857_fu_322_p2 when (and_ln856_1_fu_308_p2(0) = '1') else 
        select_ln856_fu_282_p3;
    select_ln858_1_fu_489_p3 <= 
        ap_const_lv14_1 when (empty_fu_328_p2(0) = '1') else 
        add_ln858_1_fu_483_p2;
    select_ln858_fu_400_p3 <= 
        add_ln858_fu_374_p2 when (icmp_ln859_mid211_fu_360_p2(0) = '1') else 
        v351_mid26_fu_334_p3;
        sext_ln864_fu_463_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_453_p4),64));

        sext_ln865_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln11_fu_582_p4),64));

        sext_ln866_fu_646_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln12_fu_636_p4),64));

    shl_ln1_fu_602_p3 <= (select_ln857_reg_740 & ap_const_lv14_0);
    shl_ln865_1_fu_546_p3 <= (trunc_ln864_reg_746 & ap_const_lv8_0);
    shl_ln_fu_412_p3 <= (trunc_ln864_fu_408_p1 & ap_const_lv2_0);
    tmp1_fu_433_p4 <= ((select_ln857_fu_366_p3 & trunc_ln864_1_fu_429_p1) & ap_const_lv7_0);
    tmp3_fu_562_p5 <= (((select_ln857_reg_740 & ap_const_lv5_0) & trunc_ln865_reg_762) & ap_const_lv2_0);
    tmp5_fu_618_p4 <= ((trunc_ln864_1_reg_751 & trunc_ln865_reg_762) & ap_const_lv2_0);
    trunc_ln11_fu_582_p4 <= add_ln865_1_fu_576_p2(63 downto 2);
    trunc_ln12_fu_636_p4 <= add_ln866_1_fu_630_p2(63 downto 2);
    trunc_ln864_1_fu_429_p1 <= select_ln858_fu_400_p3(6 - 1 downto 0);
    trunc_ln864_fu_408_p1 <= select_ln856_1_fu_314_p3(5 - 1 downto 0);
    trunc_ln865_fu_473_p1 <= v352_mid2_fu_392_p3(6 - 1 downto 0);
    trunc_ln_fu_453_p4 <= add_ln864_1_fu_447_p2(63 downto 2);
    v351_mid26_fu_334_p3 <= 
        ap_const_lv7_0 when (empty_fu_328_p2(0) = '1') else 
        v351_fu_120;
    v352_mid2_fu_392_p3 <= 
        ap_const_lv7_0 when (empty_70_fu_386_p2(0) = '1') else 
        v352_fu_116;
    xor_ln856_fu_290_p2 <= (icmp_ln857_fu_276_p2 xor ap_const_lv1_1);
    zext_ln857_fu_553_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln865_1_fu_546_p3),64));
    zext_ln858_fu_609_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_602_p3),64));
    zext_ln864_fu_443_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp1_fu_433_p4),64));
    zext_ln865_1_fu_572_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp3_fu_562_p5),64));
    zext_ln865_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_412_p3),64));
    zext_ln866_fu_626_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp5_fu_618_p4),64));
end behav;
